- Demo/src/main/java/com/braintreepayments/demo/MainActivity.java
Initial conditions:
- Turn on "Do not keep activities" flag in Developer Options
Scenario:
- Press Drop-In button
- Enter credit card information e.g. 4242 4242 4242 4242
- Press Buy button
Expected:
- Main Activity is in the foreground displaying the nonce
Actual:
- Demo app crashes
> Fix crash when completing the purchase and main activity is destroyed

- Braintree/src/main/java/com/braintreepayments/api/internal/AnalyticsEvent.java
When called consecutively, `connectivityManager.getActiveNetworkInfo()` may return different values. Storing the `NetworkInfo` object in a variable fixes wild NPEs in `AnalyticsEvent.getNetworkType`.
[StackOverflow link](http://stackoverflow.com/questions/28872310/connectivitymanager-getactivenetworkinfo-returns-null)
> Fix NPE with connectivityManager.getActiveNetworkInfo() in AnalyticsEvent

- Lint/build.gradle
- Lint/src/main/java/com/braintreepayments/lint/BetaDetector.java
- Lint/src/test/java/com/braintreepayments/lint/BetaDetectorTest.java
- build.gradle
Custom lint checks using the old and deprecated Lombok AST API cause an incompatibility between the Android lint and Retrolambda as described here https://github.com/evant/gradle-retrolambda/issues/96
Migrating to the new API fixes the issue.
> Migrate lint check to new PSI API

- Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java
- Braintree/src/main/java/com/braintreepayments/api/exceptions/BraintreeException.java
- Braintree/src/main/java/com/braintreepayments/api/exceptions/ConfigurationException.java
So, for debugging purposes, I would prefer to know the cause of this exception when there is one, and I don't see any harm in including it :)
> Include cause in ConfigurationException

- Braintree/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureWebView.java
There are some banks which 3DSecure website require web storage in order to work properly, specially when another 3rd party app is required in the process, such as digipass or bankid.
> Add DOM storage & DB storage to ThreeDSecureWebView

- Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java
- Braintree/src/main/java/com/braintreepayments/api/internal/IntegrationType.java
- Braintree/src/test/java/com/braintreepayments/api/BraintreeFragmentUnitTest.java
Solution for issue #252 , attaching BraintreeFragment to a child FragmentManager so that the instance can stay in the scope of a Fragment hosted by an Activity.
> Issue #252 - BraintreeFragment with child FragmentManager.

- Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java
We have in production a lot of Fatal Exception (23 in 7 days):
```
java.util.ConcurrentModificationException
    at java.util.ArrayDeque$DeqIterator.next + 625(ArrayDeque.java:625)
    at java.util.AbstractCollection.addAll + 343(AbstractCollection.java:343)
    at java.util.ArrayDeque.<init> + 197(ArrayDeque.java:197)
    at com.braintreepayments.api.BraintreeFragment.flushCallbacks + 726(BraintreeFragment.java:726)
   at com.braintreepayments.api.BraintreeFragment.onResume + 249(BraintreeFragment.java:249)
```
The only part where mCallbackQueue is **not** syncronized is **postOrQueueCallback**.
I suppose while make a copy of **mCallbackQueue** in **flushCallbacks** (line 726) an other thread call **postOrQueueCallback**
Regards
Stephan
> Use `synchronized` when adding to callback queue

- Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java
- Braintree/src/main/java/com/braintreepayments/api/PayPal.java
- Braintree/src/test/java/com/braintreepayments/api/MockFragmentBuilder.java
- Braintree/src/test/java/com/braintreepayments/api/PayPalUnitTest.java
- CHANGELOG.md
The network call to PayPal may return after the user exited the
Activity. In this case PayPal (browser) should not be opened.
- Check if the BraintreeFragment is still added to its Activity before proceeding.
- brudaswen
> Do not open PayPal (browser) if Activity is destroyed (#295)

- GooglePay/build.gradle
- VisaCheckout/build.gradle
- This PR fixes a typo with `beta1` where the `google-pay` artifact was still named `google-payment`
- @sarahkoop
- @sshropshire
> Gradle Fixup: Rename google-payment to google-pay

- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/BraintreeWalletConstants.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayRequest.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayClientUnitTest.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayRequestUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/Fixtures.kt
- Add `ELO` and `ELO_DEBIT` to `allowedCardNetworks` when "elo" supported by Braintree gateway config
- Add `setCountryCode` to `GooglePayRequest`
- @sarahkoop
- @sshropshire
> V4 Elo Support

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/CardFragment.java
- ThreeDSecure/build.gradle
- ThreeDSecure/src/main/java/com/braintreepayments/api/CardinalClient.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureRequest.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureV1UiCustomization.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureV2BaseCustomization.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureV2ButtonCustomization.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureV2ButtonType.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureV2LabelCustomization.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureV2TextBoxCustomization.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureV2ToolbarCustomization.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureV2UiCustomization.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/CardinalClientUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureRequestUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV1BrowserSwitchHelperTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV1UiCustomizationUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV2ButtonCustomizationUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV2LabelCustomizationUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV2TextBoxCustomizationUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV2ToolbarCustomizationUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV2UiCustomizationUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV2UnitTest.java
- v4_MIGRATION_GUIDE.md
- Wrap Cardinal UI customization classes in Braintree classes
- Mark Cardinal dependency as `implementation` instead of `api`
- Follows iOS PR [569](https://github.com/braintree/braintree_ios/pull/569)
- @sarahkoop
> 3DS2 UI Customization Wrapper

- CHANGELOG.md
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentClient.java
- LocalPayment/src/test/java/com/braintreepayments/api/LocalPaymentClientUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureClient.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureClientUnitTest.java
- Add null checks to client `onBrowserSwitchResult` methods
- @sarahkoop
> Add Null Checks to onBrowserSwitchResult

- CHANGELOG.md
- Demo/src/main/AndroidManifest.xml
- GooglePay/src/main/AndroidManifest.xml
- v4_MIGRATION_GUIDE.md
- Add metadata tag to `AndroidManifest.xml` in `google-pay` module to eliminate an additional integration step for merchants.
- @sarahkoop
- @sshropshire
> Update GooglePay AndroidManifest.xml

- v4_MIGRATION_GUIDE.md
- Add more documentation for upgrading from v3 rather than integrating directly with v4 (detail changes around `BraintreeFragment` and event handling)
- Remove Visa Checkout guide and add notes for Samsung Pay and Visa Checkout being not yet supported
- @sarahkoop
> Clarify Migration Guide

- BraintreeCore/src/main/java/com/braintreepayments/api/Authorization.java
- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalCheckoutRequest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalLineItem.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalRequest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalVaultRequest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalCheckoutRequestUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalVaultRequestUnitTest.java
- Make `PayPalRequest` and subclasses `Parcelable`. We previously removed this, but realized it needs to be parcelable for Drop in, so adding it back.
- Remove missed hungarian notation from `PayPalRequest`.
- @sarahkoop 
- @sshropshire
> Make PayPalRequest Parcelable

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/LocalPaymentFragment.java
- LocalPayment/src/androidTest/java/com/braintreepayments/api/LocalPaymentClientTest.java
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentClient.java
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentResult.java
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentStartCallback.java
- LocalPayment/src/test/java/com/braintreepayments/api/LocalPaymentClientUnitTest.java
- Rename `LocalPaymentTransaction` to `LocalPaymentResult`since transactions are viewed as a server-side concept
- Rename `LocalPaymentClient#approveTransaction()` to `LocalPaymentClient#approvePayment()` 
- @sshropshire
> Local Payment Result

- PayPal/src/main/java/com/braintreepayments/api/PayPalCheckoutRequest.java
- Remove incorrect docs indicating that commas are allowed in the amount on PayPalCheckoutRequest
- @sarahkoop
> Fix docs for `amount` on `PayPalCheckoutRequest`

- README.md
- There was an old JIRA in our backlog to add the Client SDK Deprecation policy to the Android README. I formatted it similarly to[ the README in iOS](https://github.com/braintree/braintree_ios#versions).
- I called out that v2.7.3 and below are unsupported since those use expired SSL certs.
@scannillo
> Client SDK deprecation policy

- BraintreeCore/src/main/java/com/braintreepayments/api/UserCanceledException.java
- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayClientUnitTest.java
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentClient.java
- LocalPayment/src/test/java/com/braintreepayments/api/LocalPaymentClientUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureClient.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureClientUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV2UnitTest.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- v4_MIGRATION_GUIDE.md
- Return `UserCanceledException` on user cancellation
- This is useful for Drop-in to differentiate between user cancellation and other errors in the payment flow
- @sarahkoop
> Return UserCanceledException on user cancellation

- BraintreeDataCollector/src/main/java/com/braintreepayments/api/DataCollector.java
- BraintreeDataCollector/src/test/java/com/braintreepayments/api/DataCollectorUnitTest.java
- CHANGELOG.md
- Card/src/main/java/com/braintreepayments/api/CardClient.java
- GooglePay/src/main/java/com/braintreepayments/api/BraintreeGooglePayWalletConstants.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- Address feedback from #393 
- Remove `DataCollector#collectRiskData()`
- Remove `DataCollector#collectPayPalDeviceData()`
- Make `DataCollector#getClientMetadataId()` private
- Rename `BraintreeWalletConstants`
- @sarahkoop
> Address v4 Audit Feedback

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureAdditionalInformation.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureAdditionalInformationUnitTest.java
* Fix typo in `ThreeDSecureAdditionalInformation#getPaymentAccountIndicator()` method name
- @sarahkoop
> Fix Setter Typo

- CHANGELOG.md
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoIsReadyToPayCallback.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
This PR creates a `VenmoClient.isReadyToPay()` method to make two assertions:
1. The merchant has Venmo enabled in their Braintree Configuration
2. The customer device has a signature verified Venmo app installed
- @sshropshire
> VenmoClient.isReadyToPay()

- CHANGELOG.md
- Defer adding SamsungPay to CHANGELOG until it can be properly tested.
- @sshropshire
> Defer adding SamsungPay to CHANGELOG

- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureRequest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureRequestUnitTest.java
- Update `ThreeDSecureRequest` to include `cardAddChallengeRequested` param when set to true or false, and not include when null.
- @kate-paypal 
- @sarahkoop
> Update `cardAddChallengeRequested` Param to Pass False

- README.md
- Rakefile
- In `v4` the `braintree` module no longer exists as a dependency, our README incorrectly tells merchants to include `com.braintreepayments.api:braintree:4.2.0`
- Update the README dependency to show a simple card import
- Update the rake release step for updating the README
- @sarahkoop
> Update README to Remove Braintree Dependency

- SamsungPay/src/main/AndroidManifest.xml
- Add `com.samsung.android.spay` to the SamsungPay `AndroidManifest.xml` `<queries>` block. 
- Add missing values to the SamsungPay `AndroidManifest.xml` that are required for SamsungPay to work.
- @sshropshire
> Fix Samsung Pay

- BraintreeCore/build.gradle
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeClientUnitTest.java
- CHANGELOG.md
- Bump `browser-switch` version to `2.0.2` 
- Add package-private `BraintreeClient#getBrowserSwitchResult()` method.
- @sshropshire
> Get Browser Switch Result

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClientParams.java
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeClientUnitTest.java
- CHANGELOG.md
- Create a new `BraintreeClient` instructor that allows for a custom `returnUrlScheme` for browser and app switching
- Cleanup random lint errors
- @sshropshire
> BraintreeClient Custom URL Scheme Constructor

- BraintreeCore/src/test/java/com/braintreepayments/api/ConfigurationUnitTest.java
- CHANGELOG.md
- SamsungPay/src/main/java/com/braintreepayments/api/SamsungPayMapAcceptedCardBrands.java
- SamsungPay/src/test/java/com/braintreepayments/api/SamsungPayInternalClientUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/Fixtures.kt
- Add additional alias for Amex in `SamsungPay` (fixes #430)
- Update `Configuration` fixture for SamsungPay
- @sshropshire
> Fix SamsungPay Amex Issue

- BraintreeDataCollector/build.gradle
- CHANGELOG.md
- Make `:BraintreeCore` an `api` dependency for `:BraintreeDataCollector` (Fixes #437)
- @sshropshire
> Mark BraintreeCore as api dependency for BraintreeDataCollector.

- CHANGELOG.md
- Venmo/src/main/java/com/braintreepayments/api/VenmoRequest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoRequestUnitTest.java
- As part of Drop-in updates, we want to allow merchants to set a `VenmoRequest` on their `DropInRequest` - similar to what they do for PayPal and Google Pay. To make that change in Drop-in, `VenmoRequest` needs to be parcelable.
- @sarahkoop
> Make VenmoRequest Parcelable

- BraintreeCore/build.gradle
- CHANGELOG.md
* Bump `work-runtime` version to `2.7.0`
* Bump `browser-switch` version to `2.1.1`
> Update Browser Switch and Work Manager

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java
- v4_MIGRATION_GUIDE.md
- Mention conflicting intent scenario in v4_MIGRATION_GUIDE (Addresses [braintree-android-drop-in #296](https://github.com/braintree/braintree-android-drop-in/issues/296))
> Update Migration Guide with Conflicting Intent Scenario 

- CHANGELOG.md
- Card/build.gradle
- Demo/src/main/java/com/braintreepayments/demo/GooglePayFragment.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayRequest.java
- TestUtils/build.gradle
- UnionPay/build.gradle
- Update doc string to note that `googleMerchantId` is optional
- Remove setting merchant ID from demo app
- @sarahkoop
> Make Google Pay Merchant ID Explicitly Optional

- AmericanExpress/build.gradle
- BraintreeCore/build.gradle
- BraintreeDataCollector/build.gradle
- Card/build.gradle
- Card/src/test/java/com/braintreepayments/api/CardClientUnitTest.java
- Demo/build.gradle
- GooglePay/build.gradle
- LocalPayment/build.gradle
- PayPal/build.gradle
- SamsungPay/build.gradle
- SharedUtils/build.gradle
- TestUtils/build.gradle
- ThreeDSecure/build.gradle
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV1UnitTest.java
- UnionPay/build.gradle
- Venmo/build.gradle
- VisaCheckout/build.gradle
- build.gradle
- Move dependency libraries and versions to top-level `build.gradle` and standardize versions across modules (where possible)
- This should make it easier to keep dependency versions the same across modules, and to make updates to versions in the future.
- With this update, we lose the Android Studio highlighting/auto-update keyboard shortcut when a newer library is available, but this suggested dependency updates can still be found in Android Studio under `File` > `Project Structure` > `Suggestions`. 
- Overall, the ability to keep dependency versions aligned and ensure that they are all updated together seems higher priority than the keyboard shortcut, but we will need to make it a regular practice to check for suggestions. 
**Note**: This PR organizes the dependencies into a single …
> Standardize Gradle Dependencies

- v4_MIGRATION_GUIDE.md
- Fix migration guide typo related to PayPal Browser Switch
- Add a section to the migration guide for multiple deep-link targets (Fixes #488)
> Fix Migration Guide Typo and Add Section on Multiple Deep Link Targets

- BraintreeCore/src/main/java/com/braintreepayments/api/AuthorizationProvider.java
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java
- BraintreeCore/src/main/java/com/braintreepayments/api/ClientTokenCallback.java
- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/api/BraintreeClientFactory.java
- Demo/src/main/java/com/braintreepayments/api/DemoAuthorizationProvider.java
- Demo/src/main/java/com/braintreepayments/demo/DemoActivity.java
- TestUtils/src/main/java/com/braintreepayments/api/Fixtures.kt
- Venmo/src/main/java/com/braintreepayments/api/VenmoAccountNonce.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoAccountNonceUnitTest.java
- Fix issue where null value causes VenmoAccountNonce#fromJSON() to throw.
- Delay release of `AuthorizationProvider` until we finalize the interface (see [discussion](https://github.com/braintree/braintree_android/discussions/496))
> Fix Venmo Issue and Hide Authorization Loader

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/DemoViewModel.java
- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- LISTENER_MIGRATION.md
- PayPal/build.gradle
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalInternalClient.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalLifeCycleObserver.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalListener.java
- PayPal/src/test/java/com/braintreepayments/api/MockPayPalInternalClientBuilder.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalInternalClientUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalLifecycleObserverUnitTest.java
- Add `PayPalListener` to receive results from the PayPal flow
- Deprecate methods requiring a callback in favor of listener pattern
- Move API logic to `PayPalInternalClient`
> PayPal - Encapsulate Browser Switch Logic

- CHANGELOG.md
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentLifecycleObserver.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalLifeCycleObserver.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureLifecycleObserver.java
- Fix for #500
- Resolve issue where `onResume()` and `onNewIntent()` may be called out of order on some Android API versions
> Android 9 Browser Switch Fix

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeClientUnitTest.java
- Add internal constructor for `ClientTokenProvider` with `sessionId` and `integrationType` overrides for use in DropIn.
> Add Internal BraintreeClient Constructor with ClientTokenProvider

- BraintreeCore/src/main/java/com/braintreepayments/api/UserCanceledException.java
- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayActivityResultContract.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayActivityResultContractUnitTest.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayClientUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- SamsungPay/src/main/java/com/braintreepayments/api/SamsungPayInternalClient.java
- SamsungPay/src/test/java/com/braintreepayments/api/SamsungPayInternalClientUnitTest.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureClient.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureClientUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoActivityResultContractUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- build.gradle
- Add `isExplicitCancellation` parameter to `UserCanceledException`
- @jaxdesmarais 
- @mattwylder 
- @sarahkoop
> Add `isExplicitCancellation` to `UserCanceledException`

- CHANGELOG.md
- SharedUtils/src/main/java/com/braintreepayments/api/BraintreeSharedPreferences.java
- This PR updates `BraintreeSharedPreferences` to defensively no-op when a reference to `EncryptedSharedPreferences` cannot be obtained.
- Fixes #561
> Fix BraintreeSharedPreferences Instant App Crash

- BraintreeDataCollector/src/main/java/com/braintreepayments/api/KountDataCollector.java
- BraintreeDataCollector/src/test/java/com/braintreepayments/api/KountDataCollectorUnitTest.java
- CHANGELOG.md
- There have been some issues reported with custom Kount integrations that result in duplicate symbol errors.
- This PR references Kount only when needed, which should prevent the JVM from loading it if it isn't used by the SDK.
- @sshropshire
> Lazily Reference Kount

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeError.java
- BraintreeCore/src/test/java/com/braintreepayments/api/ErrorsWithResponseUnitTest.java
- CHANGELOG.md
- TestUtils/src/main/java/com/braintreepayments/api/Fixtures.kt
- For duplicate payment method tokenization errors, it is helpful to have the actual error code returned to provide more meaningful feedback to the merchant.
- This work will help resolve [DropIn Issue #357](https://github.com/braintree/braintree-android-drop-in/issues/357)
- @sshropshire
> Propagate Error Code From GraphQL and REST Responses

- CHANGELOG.md
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutClient.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalNativeCheckoutClientUnitTest.java
NXO can be constructed with less parameters since it doesn't need to app switch.
- Add new `PayPalNativeCheckoutClient` that requires only a `BraintreeClient` instance.
- Add new `PayPalNativeCheckoutClient#launchNativeCheckout` method that launches native checkout without throwing.
- Deprecate `PayPalNativeCheckoutClient` constructor that requires both `Fragment` and `BraintreeClient` instances.
- Deprecate `PayPalNativeCheckoutClient#tokenizePayPalAccount` method that throws an exception.
- @sshropshire
> Refactor NXO Constructor

- PayPalDataCollector/src/main/java/com/braintreepayments/api/PayPalDataCollector.java
- PayPalDataCollector/src/main/java/com/braintreepayments/api/PayPalDataCollectorRequest.java
- PayPalDataCollector/src/test/java/com/braintreepayments/api/MagnesInternalClientUnitTest.java
- PayPalDataCollector/src/test/java/com/braintreepayments/api/PayPalDataCollectorRequestUnitTest.java
- This PR updates the `clientMetadataId` to `riskCorrelationId` on `PayPalDataCollector` to make it clearer.
- This shouldn't be considered a breaking change since Java / Kotlin interop [doesn't generate named parameters](https://discuss.kotlinlang.org/t/what-is-the-reason-for-not-allowing-named-arguments-for-java-interop/4571) for Java methods. (also verified this in a sample project)
- @sshropshire
> Rename `clientMetadataId` parameter to `riskCorrelationId`

- CHANGELOG.md
- PayPalNativeCheckout/build.gradle
- build.gradle
- Bumping the native version to add support for OTP
-
> Bumping native version

- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutClient.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalNativeCheckoutClientUnitTest.java
- add analytics events for PayPal Native Checkout
- add tests for analytics
- These events match the [iOS analytics PR as closely as possible](https://github.com/braintree/braintree_ios/pull/862) - missing events are due to differences in how iOS vs Android handles the implementation
> Add Analytics for PayPal Native Checkout

- CHANGELOG.md
- PayPalNativeCheckout/build.gradle
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutClient.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalNativeCheckoutClientUnitTest.java
- build.gradle
- Bumping the native version
- Adding in a call to be able to distinguish between nxo and bt sessions
-
> Adding analytics for nxo and bumping native version

- BraintreeCore/build.gradle
- BraintreeDataCollector/build.gradle
- Demo/build.gradle
- GooglePay/build.gradle
- PayPalDataCollector/build.gradle
- SamsungPay/build.gradle
- SharedUtils/build.gradle
- TestUtils/build.gradle
- ThreeDSecure/build.gradle
- VisaCheckout/build.gradle
- This PR removes explicit declaration of the `buildToolsVersion` property for all modules
- This property has not been needed since Android [Gradle Plugin Version 3.0.0](https://developer.android.com/studio/releases/gradle-plugin#3-0-0)
- @sshropshire
> Remove Build Tools Version From build.gradle Files

- CHANGELOG.md
- SharedUtils/src/main/java/com/braintreepayments/api/BraintreeSharedPreferences.java
- This PR adds an explicit key alias for encrypted shared prefs (potential fix for #604)
- @sshropshire
> Add Explicit Master Key Alias for Encrypted Shared Prefs

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java
- BraintreeCore/src/main/java/com/braintreepayments/api/ConfigurationCache.java
- BraintreeCore/src/main/java/com/braintreepayments/api/ConfigurationLoader.java
- BraintreeCore/src/main/java/com/braintreepayments/api/ConfigurationLoaderCallback.java
- BraintreeCore/src/main/java/com/braintreepayments/api/ConfigurationLoaderResult.java
- BraintreeCore/src/main/java/com/braintreepayments/api/UUIDHelper.java
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeClientUnitTest.java
- BraintreeCore/src/test/java/com/braintreepayments/api/ConfigurationCacheUnitTest.java
- BraintreeCore/src/test/java/com/braintreepayments/api/ConfigurationLoaderUnitTest.java
- BraintreeCore/src/test/java/com/braintreepayments/api/UUIDHelperUnitTest.java
- CHANGELOG.md
- SharedUtils/src/androidTest/java/com/braintreepayments/api/BraintreeSharedPreferencesTest.java
- SharedUtils/src/main/java/com/braintreepayments/api/BraintreeSharedPreferences.java
- SharedUtils/src/main/java/com/braintreepayments/api/BraintreeSharedPreferencesException.java
- SharedUtils/src/main/java/com/braintreepayments/api/UnexpectedException.java
- TestUtils/src/main/java/com/braintreepayments/api/BraintreeActivityTestRule.java
- TestUtils/src/main/java/com/braintreepayments/api/MockConfigurationLoaderBuilder.java
- TestUtils/src/main/java/com/braintreepayments/api/SharedPreferencesHelper.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoSharedPrefsWriter.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoSharedPrefsWriterUnitTest.java
- build.gradle
- Allow `BraintreeSharedPreferences` to gracefully degrade when `EncryptedSharedPreferences` fails (fix for #619)
- @sshropshire
> Add Defensive Guards to Prevent Crashes Related to Jetpack Security Crypto

- CHANGELOG.md
- PayPalNativeCheckout/build.gradle
- We need to bump the native version cause its pointing to the old cardinal dependency that is notifying google of an outdated version
-
> Bumping native version for cardinal fix

- CHANGELOG.md
- build.gradle
* BraintreeCore
* Bump `browser-switch` version to `2.3.2`
> Bump Browser Switch to 2.3.2

- build.gradle
- Update build script to update Jetpack Room dependency to an M1 Mac friendly variant
- Fallback to Java 7 friendly Room version during CI build
- @sshropshire
> M1 Mac Build Script Fix

- .github/workflows/release.yml
- AmericanExpress/build.gradle
- BraintreeCore/build.gradle
- BraintreeCore/src/main/java/com/braintreepayments/api/Configuration.kt
- BraintreeDataCollector/build.gradle
- Card/build.gradle
- GooglePay/build.gradle
- LocalPayment/build.gradle
- PayPal/build.gradle
- PayPalDataCollector/build.gradle
- PayPalNativeCheckout/build.gradle
- SEPADirectDebit/build.gradle
- SamsungPay/build.gradle
- SharedUtils/build.gradle
- ThreeDSecure/build.gradle
- UnionPay/build.gradle
- Venmo/build.gradle
- VisaCheckout/build.gradle
- build.gradle
- Replace Javadoc with [Dokka](https://kotlin.github.io/dokka) to generate docs for both Java and Kotlin
- Add `./gradlew dokkaHtmlMultiModule` to the GitHub actions release workflow
- Output docs in the `./docs` folder so we can host docs via GitHub Pages  
- @sshropshire
> Generate Documentation With Dokka

- build.gradle
- Lowering `androidx.core:core-ktx` dependency version to `1.1.0` since newer versions [require Java 8](https://developer.android.com/jetpack/androidx/releases/core#1.2.0-alpha02).
- @sshropshire
> Bump Down `androidx.core:core-ktx` to Version 1.1.0

- BraintreeCore/src/main/java/com/braintreepayments/api/InvalidArgumentException.kt
- The `InvalidArgumentException` constructor is used in the `three-d-secure` module
- @sshropshire
> Make InvalidArgumentException Constructor Visible to LIBRARY_GROUP

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java
- CHANGELOG.md
- `BraintreeClient` forces `applicationId` to lowercase when creating a `returnUrlScheme` for browser switching
- Uppercase characters are [valid URL scheme characters](https://stackoverflow.com/a/3641782)
- We should remove this restriction (See [braintree-android-drop-in #379](https://github.com/braintree/braintree-android-drop-in/issues/379))
- @sshropshire
> Allow Uppercase Characters in Return URL Scheme

- CHANGELOG.md
- build.gradle
- Bump androidx `security-crypto` library to latest version
- @sshropshire
> Update androidx security-crypto to 1.1.0-alpha04

- CHANGELOG.md
- ThreeDSecure/src/main/AndroidManifest.xml
- Apply `Theme.AppCompat` to `ThreeDSecureActivity`
- Possible fix for [braintree-android-drop-in #326](https://github.com/braintree/braintree-android-drop-in/issues/326)
- @sshropshire
> Apply `Theme.AppCompat` to ThreeDSecureActivity

- CHANGELOG.md
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutClient.java
- Changing the intent from native to use the one from the request
-
> Changing nxo intent to use the one from the PayPalNativeCheckoutRequest

- CHANGELOG.md
- SamsungPay/src/main/java/com/braintreepayments/api/SamsungPayNonce.java
- SamsungPay/src/test/java/com/braintreepayments/api/SamsungPayInternalClientUnitTest.java
- SamsungPay/src/test/java/com/braintreepayments/api/SamsungPayNonceUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/Fixtures.kt
- Support legacy `singleUseToken` property when parsing Samsung Pay response (fixes #668)
- @sshropshire
> Support SamsungPay Single Use Token

- CHANGELOG.md
- build.gradle
- Revert androidx `security-crypto` dependency to `1.1.0-alpha03` (`1.1.0-alpha04` requires a compile target of 33)
- @sshropshire
> Revert androidx `security-crypto` dependency to `1.1.0-alpha03`

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeClientUnitTest.java
- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalNativeCheckoutClientUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/MockBraintreeClientBuilder.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureClient.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureClientUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV1UnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV2UnitTest.java
- In rare cases, browser switch fails in production for some users. It's difficult to reproduce this issue.
- The browser switch library provides more information that may be helpful to diagnose an issue 
- Appending original browser switch error message to error output will help resolve issues like #630
- @sshropshire
> Append Browser Switch Original Error Message on Failure

- BraintreeCore/src/main/java/com/braintreepayments/api/ClientToken.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/InvalidAuthorization.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/TokenizationKey.kt
- Fixes for DropIn issue [#396](https://github.com/braintree/braintree-android-drop-in/issues/396)
- DropIn requires visibility of these classes to change behavior
- @sshropshire
> Make `Authorization` Subclasses Library-Restricted 

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeClientUnitTest.java
- CHANGELOG.md
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentClient.java
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentLifecycleObserver.java
- LocalPayment/src/test/java/com/braintreepayments/api/LocalPaymentClientUnitTest.java
- LocalPayment/src/test/java/com/braintreepayments/api/LocalPaymentLifecycleObserverUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalLifeCycleObserver.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalLifecycleObserverUnitTest.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureClient.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureLifecycleObserver.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureClientUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureLifecycleObserverUnitTest.java
- Add `BraintreeClient#deliverBrowserSwitchResultFromNewTask()` method to allow browser switch results to be captured manually when `BraintreeClient#launchesBrowserSwitchAsNewTask()` is set to true.
- @sshropshire
> Add `BraintreeClient#deliverBrowserSwitchResultFromNewTask()` method

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- Fix issue that causes a null pointer exception when `PayPalClient` attempts to notify success or failure when the listener is `null`
- @sshropshire
> Paypal Client Add Listener `null` Check

- README.md
updated link, since there is a `v4.9.0+_MIGRATION_GUIDE.md`, people should be directed there over the `v4._MIGRATION_GUIDE.md`
> v4.9.0+_MIGRATION_GUIDE.md mentioned

- BraintreeCore/src/main/java/com/braintreepayments/api/UUIDHelper.kt
- `UUIDHelper` is used accross module boundaries and needs to be library-restricted
- @sshropshire
> Make UUIDHelper Library Restricted

- BraintreeCore/src/main/java/com/braintreepayments/api/DeviceInspector.kt
- `DeviceInspector` needs to be visible across module boundaries so `VenmoClient` can use it
- Make `DeviceInspector` library-restricted to prevent merchant use
- @sshropshire
> Make `DeviceInspector` Library Restricted

- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayCardNonce.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayCardNonceUnitTest.java
- Fix for https://github.com/braintree/braintree-android-drop-in/issues/405
- Add `isNetworkTokenized` to `Parcelable` implementation for `GooglePayNonce`
- @sshropshire
> Fix `GooglePayNonce#isNetworkTokenized` Parcelable error

- BraintreeCore/src/main/java/com/braintreepayments/api/ApiClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/AuthorizationCallback.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/ConfigurationLoader.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/ConfigurationLoaderCallback.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/PreferredPaymentMethodsClient.kt
- SharedUtils/src/main/java/com/braintreepayments/api/HttpResponseCallback.kt
- `fun interface` types in Kotlin rely on Java 8
- By removing these functional interfaces, we can keep Java 7 support
- All of the `fun interface` types in this PR are marked `library-private` or are `internal`
- To prevent a breaking change, we should avoid refactoring Java callback types to adhere to [SAM](https://kotlinlang.org/docs/fun-interfaces.html)
- @sshropshire
> Remove `fun` Interfaces

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureClient.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV2UnitTest.java
- build.gradle
- fix for #642 
- In `ThreeDSecureClient`, before launching `ThreeDSecureActivity`, we add check for `TransactionTooLargeException`
@sshropshire @KunJeongPark
> Fix for 3DS TransactionTooLargeException

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/CardinalClient.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureClient.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/CardinalClientUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/MockCardinalClientBuilder.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureClientUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureV2UnitTest.java
- Guard `ThreeDSecureClient` against potential Cardinal SDK runtime exceptions
- @sshropshire
> Catch All Cardinal Runtime Errors

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeClientUnitTest.kt
- CHANGELOG.md
- Demo/src/androidTest/java/com/braintreepayments/demo/test/PayPalManualBrowserSwitchTest.java
- Demo/src/main/java/com/braintreepayments/demo/LocalPaymentFragment.java
- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- Demo/src/main/res/values/strings.xml
- Demo/src/main/res/xml/settings.xml
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentClient.java
- LocalPayment/src/test/java/com/braintreepayments/api/LocalPaymentClientUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- build.gradle
- v4.9.0+_MIGRATION_GUIDE.md
- Create a separate integration pattern for merchants who want more control over the browser switch lifecycle
- Depends on https://github.com/braintree/browser-switch-android/pull/64
- @sshropshire
> Allow Manual Browser Switch Handling

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalCheckoutRequest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalInternalClient.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalRequest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalInternalClientUnitTest.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutRequest.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeRequest.java
- Remove appending query parameters to the URL from the PayPal flow and instead pass the `user_action` into the `experience_profile`
- Not sure the historical context on passing this as a query item, but there is no regression on web when passing this in the `experience_profile` instead
This is the result of setting `request.setUserAction()` to `USER_ACTION_COMMIT` in both the web and MXO checkout flows with the changes in this PR:
| Web | MXO |
|-----|-----|
|![android-web-commit](https://github.com/braintree/braintree_android/assets/20733831/35826892-f575-499d-a7f7-171f294f61d7)|![mxo-commit](https://github.com/braintree/braintree_android/assets/20733831/1469c53b-6a09-443b-887c-e2dfede88433)|
> Fix MXO User Action Bug

- CHANGELOG.md
- The `PayPalNativeCheckout` entry got placed under the `4.32.0` section - this moves them to unreleased as the PR was just merged in and not yet released
> Update NXO notes in CHANGELOG

- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayCardNonce.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayCardNonceUnitTest.java
- Add `getCardNetwork` to `GooglePayCardNonce`
- Update test to add `getCardNetwork`
- Verified card network is returned as expected in demo app
- **Note:** we do not have a way to explicity test Maestro cards since Google does not provide them in their test card suite and we do not not have access to a valid Maestro card to add to the Google Wallet
> Add `getCardNetwork` to `GooglePayCardNonce`

- CHANGELOG.md
- build.gradle
- Revert Kotlin version to `1.7.10`
- @sshropshire
> Revert Kotlin Version to 1.7.10

- Braintree/src/main/java/com/braintreepayments/api/LocalPayment.java
- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/LocalPaymentsActivity.java
- Seems like something changed with client tokens/the gateway and `configuration.getPayPal().isEnabled()` now returns for merchants enabled for PayPal/Local Payment Methods. We note that `isEnabled` is deprecated and switching to use `isPayPalEnabled` returns the correct result for LPM enabled merchants.
- The tokenization key we were using didn't support LPMs - pulled the one being used from iOS in the LPM ViewController to test things are now working as expected.
> [3.x] Fix LPM Configuration Bug

- CHANGELOG.md
- Demo/build.gradle
- Demo/src/main/AndroidManifest.xml
- PayPalNativeCheckout/build.gradle
- README.md
- Update PayPalNativeCheckout module min SDK version to 23 to prevent crashes on lower API versions
- Fix lint error in Demo app
- @sarahkoop
> Update PayPalNativeCheckout Min SDK

- CHANGELOG.md
- Demo/build.gradle
- SharedUtils/src/main/java/com/braintreepayments/api/SynchronousHttpClient.java
- TestUtils/src/main/java/com/braintreepayments/api/Fixtures.kt
- build.gradle
- Update compileSdkVersion and targetSdkVersion to API 34 (Android 14) 
- TODO: Update browser switch version when released with [Android 14 support change](https://github.com/braintree/browser-switch-android/pull/69)
- @sarahkoop
> Android 14 Support

- CHANGELOG.md
- build.gradle
- Bump `browser-switch` version to `2.6.0`
- @sshropshire
> Bump Browser Switch to Version 2.6.0

- CHANGELOG.md
- build.gradle
* ThreeDSecure
* Bump Cardinal version to `2.2.7-5`
- @sshropshire
> Bump Cardinal Version to 2.2.7-5

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeOptions.kt
- CHANGELOG.md
- Make BraintreeClient Constructor with BraintreeOptions `library-private`
- @sshropshire
> Make BraintreeClient Constructor with BraintreeOptions Library Private

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/VenmoFragment.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoActivityResultContract.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoApi.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoAuthChallengeCallback.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoAuthChallengeResultCallback.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoCreatePaymentAuthRequestCallback.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoLauncher.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoLauncherCallback.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoPaymentAuthRequest.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoPaymentAuthRequestCallback.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoPaymentAuthResult.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoTokenizeCallback.java
- Venmo/src/test/java/com/braintreepayments/api/MockVenmoApiBuilder.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoActivityResultContractUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoApiUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoLauncherUnitTest.java
- v5_MIGRATION_GUIDE.md
- Rename Venmo APIs to `createPaymentAuthRequest` and `tokenize` and rename associated result objects and callbacks
- Cleanup VenmoClient - remove unused static strings and use lambdas
- @sarahkoop
> Rename Venmo APIs

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/CardFragment.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/CardinalResultCallback.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureActivityResultContract.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureClient.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureLauncher.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureLauncherCallback.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecurePaymentAuthResult.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureResult.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureResultCallback.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureActivityResultContractUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureClientUnitTest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureLauncherUnitTest.java
- v5_MIGRATION_GUIDE.md
- Rename 3DS APIs to follow `createPaymentAuthRequest` and `tokenize` pattern
- Remove internal `continuePerformVerification` method and rename `startVerificationFlow` internal method to `sendAnalyticsAndCallbackResult` (this method can also likely be refactored and removed when analytics are updated).
- 3DS is slightly different than the other modules because it uses a single `ThreeDSecureResult` object for both steps of the flow, there is also a single callback for those results that is used internally and externally. For now, I left the `ThreeDSecureResult` object naming the same and kept the callback. I've added TODOs to refactor that object and those callbacks in the PR to migrate to a single result object pattern.
- @sarahkoop
> Rename 3DS APIs

- CHANGELOG.md
- PayPalNativeCheckout/build.gradle
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutClient.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeRequest.java
- Creating the auth config for android for merchant passed email
-
> Update mxo 1.2.0

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureActivity.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureLookup.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureActivityUnitTest.java
- Remove implementation of `CardinalValidateReceiver`
- Make `ThreeDSecureLookup` empty constructor package-private
- @sarahkoop
> Resolve 3DS Next Major Version Notes

- Venmo/src/main/java/com/braintreepayments/api/VenmoAnalytics.kt
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoAnalyticsUnitTest.kt
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- Update analytics events throughout Venmo flow with new FPTI analytics events
- @sarahkoop
> Update Venmo with FPTI Analytics Events

- CHANGELOG.md
- SharedUtils/src/main/java/com/braintreepayments/api/LoggingUtils.kt
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- Fix NPE in `VenmoClient` when listener is null by checking if listener exists before returning success or failure (does nothing on result without listener, but does not crash) 
- Fixes #832 
- @sarahkoop
> VenmoListener NPE Fix

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- Propagate errors fetching configuration (which propagates authorization errors under the hood) to `PayPalListener` when auth is invalid or config is unable to be fetched, rather than returning a generic error message that PayPal is not enabled.
- Note: This will return the merchant's own auth error defined in their `ClientTokenProvider` if an error is thrown at that level, or will propagate config fetching errors or other auth errors (ex if ClientTokenProvider is null).
- Fixes #821 
- @sarahkoop
> Return Auth/Config Error in PayPalClient

- Card/src/main/java/com/braintreepayments/api/CardAnalytics.kt
- Card/src/main/java/com/braintreepayments/api/CardClient.java
- Card/src/test/java/com/braintreepayments/api/CardAnalyticsUnitTest.kt
- Card/src/test/java/com/braintreepayments/api/CardClientUnitTest.java
- Update card tokenize analytics with new FPTI events
- @sarahkoop
> Add Card FPTI Analytics Events

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/VenmoFragment.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoLauncher.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoLauncherUnitTest.java
- Replace `FragmentActivity` with `Context` where possible in `VenmoClient` methods
- Move `showVenmoAppInGooglePlayStore` method to `VenmoLauncher`
- @sarahkoop
> Remove Activity from VenmoClient

- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayCapabilities.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayInternalClient.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayIsReadyToPayCallback.java
- GooglePay/src/main/java/com/braintreepayments/api/ReadyForGooglePayRequest.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayInternalClientUnitTest.kt
- Remove references to `FragmentActivity` from `GooglePayClient` and replace with `Context` where possible to make integration more flexible.
- @sarahkoop
> Remove FragmentActivity from GooglePayClient

- AmericanExpress/src/main/java/com/braintreepayments/api/AmericanExpressAnalytics.kt
- AmericanExpress/src/main/java/com/braintreepayments/api/AmericanExpressClient.java
- AmericanExpress/src/test/java/com/braintreepayments/api/AmericanExpressAnalyticsUnitTest.kt
- AmericanExpress/src/test/java/com/braintreepayments/api/AmericanExpressClientUnitTest.java
- Update `AmericanExpressClient` to send FPTI analytics events
- Update `AmericanExpressAnalytics` to be a simple object rather than enum
- @sarahkoop
> Send FPTI Analytics Events in American Express

- build.gradle
- Update browser switch dependency to use snaphots while developing browser switch v3 (to be updated to full release major version before v5 release)
- ~[] Added a changelog entry~
- @sarahkoop
> Use Browser Switch Snapshots

- PayPalMessaging/src/main/java/com/braintreepayments/api/paypalmessaging/PayPalMessagingView.kt
- PayPalMessaging/src/test/java/com/braintreepayments/api/paypalmessaging/PayPalMessagingViewUnitTest.kt
- Rename `PayPalMessagingClient` to `PayPalMessagingView`
- [iOS conversation where this decision was made](https://github.com/braintree/braintree_ios/pull/1153#discussion_r1431811348)
- tl;dr: when implementing the feature in a demo app it became apparent that adding a view called a client seemed a bit odd. Since this is the first module we have that just contains UI we will establish this as our pattern moving forward.
> Rename `PayPalMessagingClient` to `PayPalMessagingView`

- ShopperInsights/build.gradle
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsAnalytics.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/ShopperInsightsClientUnitTest.kt
https://paypal.atlassian.net/browse/DTBTSDK-3296
- Adding methods for merchants to send analytic events for shopper insights feature.
- @saperi22
> Shopper Insights - Merchant analytics

- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalLauncher.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalPaymentAuthCallback.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalLauncherUnitTest.java
- Remove `FragmentActivity` parameter from `PayPalClient` methods in favor of `Context`
- Move `assertCanPerformBrowserSwitch` from `PayPalClient` to `PayPalLauncher` since the launcher handles starting the browser switch now
- ~[ ] Added a changelog entry~ 
- @sarahkoop
> Remove Activity from PayPalClient

- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureLauncher.java
- Update ThreeDSecureLauncher constructor to take more generic ComponentActivity rather than FragmentActivity (we don't use any FragmentActivity specific attributes and ComponentActivity is more compose-compatible)
- Update doc strings for ThreeDSecureLauncher public methods
- @sarahkoop
> Update ThreeDSecureLauncher Constructor

- GooglePay/src/main/java/com/braintreepayments/api/GooglePayLauncher.java
- Update GooglePayLauncher constructor to take more generic `ComponentActivity` rather than `FragmentActivity` (we don't use any FragmentActivity specific attributes and ComponentActivity is more compose-compatible)
- Add doc strings for GooglePayLauncher public methods
- @sarahkoop
> Update GooglePayLauncher Constructor Params

- Venmo/src/main/java/com/braintreepayments/api/VenmoLauncher.java
- Update VenmoLauncher to take `ComponentActivity` rather than `FragmentActivity` since it is more generic and we don't need FragmentActivity attributes
- @sarahkoop
> Update VenmoLauncher to use ComponentActivity

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalLineItem.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalLineItemUnitTest.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutLineItem.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalLineItemUnitTest.java
- Added the ability for merchants to pass imageUrl, upcCode, upcType in PayPalLineItem.
- @vankads
> Adding imageUrl, upcType, upcCode to PayPalLineItem

- .github/PULL_REQUEST_TEMPLATE.MD
Let's make it a little easier for engineers from other PayPal teams to share with us the priority of getting their changes reviewed and released.
I added a section to the bottom of the PR template that tries to contextualize team deadlines for getting certain changes released without giving away internal business info.
It's very small, but hopefully adopting this can help us help our colleagues deliver code changes on time without needing to ping us outside of the PR review.
Assuming folks are ok with this for Android, I'll go ahead and update iOS and Drop-in repo PR templates, too
> Clarify Pull Request urgency

- PayPalMessaging/build.gradle
- build.gradle
This work is going into the `paypal-messaging-feature` branch
- Now that a version of the SDK has been released we can add it as a dependency and pick back up on wrapping this feature
@jaxdesmarais
> Add PayPal Messaging Dependency

- Demo/src/main/java/com/braintreepayments/demo/VenmoFragment.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoRequest.java
- Send `MULTI_USE` instead of `SINGLE_USE` to the `VenmoPaymentMethodUsage` param in the Venmo request when vault is enabled
> Update Venmo demo to send MULTI_USE when vault is enabled

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeHttpClient.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeHttpClientUnitTest.kt
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- PayPalDataCollector/src/main/java/com/braintreepayments/api/MagnesInternalClient.java
- ShopperInsights/src/main/java/com/braintreepayments/api/EligiblePaymentsApi.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/EligiblePaymentsCallback.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsApi.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/EligiblePaymentsApiUnitTest.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/ShopperInsightsClientUnitTest.kt
- Added network call for eligible payments api
- Updated demo app to show response
@MaxHastingsPP
> Add network call for shopper insights

- gradle/gradle-publish.gradle
- Javadocs task when run with AGP 8 is currently broken - fix by removing invalid classpath
@sarahkoop
> Fix Javadocs Task for AGP 8

- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/ShopperInsightsClientUnitTest.kt
- Removed the PayPal and Venmo app installed checks from the Shopper Insights module - the API call is now always executed.
- Rearrange a few analytics calls to match iOS
> Remove App Check From Shopper Insights and Analytics Updates

- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/ApiClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeHttpClient.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/AnalyticsClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/ApiClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeHttpClientUnitTest.kt
- SharedUtils/src/main/java/com/braintreepayments/api/HttpResponseCallback.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/EligiblePaymentsApi.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/EligiblePaymentsApiUnitTest.kt
- Add the `PayPal-Client-Metadata-Id` header to the Shopper Insights API call
- Pass `addtionalHeaders` all the way down to `BraintreeHttpClient` to be added to the request
- Added named parameters to certain call sites to utilize the empty map default value while keeping the callback param the last in the list
> Add PayPal-Client-Metadata-Id to Shopper Insights API Call

- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- Demo/src/main/res/layout/fragment_shopping_insights.xml
- Demo/src/main/res/navigation/nav_graph.xml
- Demo/src/main/res/values/strings.xml
See similar [iOS PR](https://github.com/braintree/braintree_ios/pull/1185). The goal is to align our Demo app's functionality for QA testers to easily use.
- Add Venmo & PayPal Vault buttons to ShopperInsights demo for use after `getRecommendedPaymentMethods()` returns a result
- Add Venmo & PP listeners
- Add navigation logic to nonce creation & transaction.sale() screen
- Disable Venmo & PP buttons until `getRecommendedPaymentMethods()` returns `isRecommended` booleans
- Add default email & phone test values to trigger mocked API response
- This demo requires that Settings select "Client Token" as the auth type
- We should consider returning an error to the merchant if they attempt to use a tokenization key in follow up PRs
- There's a mixed use of "shopper" and "shopping" terminology …
> [Shopper Insights] Demo App Parity

- CHANGELOG.md
- Venmo/src/main/java/com/braintreepayments/api/VenmoApi.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoRequest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoApiUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoRequestUnitTest.java
-   Add `setIsFinalAmount()` to `VenmoRequest`
- This removes the text "Subject to change" as seen below
| Final Amount = false (default) | Final Amount = true |
|-----|-----|
|![Screenshot_20240214-084546](https://github.com/braintree/braintree_android/assets/20733831/d8480eeb-10b7-4102-8431-813973f2435a)|![Screenshot_20240214-084609](https://github.com/braintree/braintree_android/assets/20733831/1264dee0-706c-409d-8fa2-6bbba4544743)|
@jaxdesmarais
> Venmo Final Amount

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/CardinalClient.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/CardinalClientUnitTest.kt
- Call Cardinal cleanup method to resolve memory leak from `Cardinal.getInstance`
- Verified via Leak Canary that the `getInstance` memory leak is gone
- Note: there is still a memory leak on `Cardinal.cca_continue` that will be resolve in a future Cardinal release
@jaxdesmarais
> Cardinal Cleanup Method

- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsClient.kt
- Added docStrings for country restrictions on function `getRecommendedPaymentMethods`
[ ] Added a changelog entry
[ ] Relevant test coverage
@KunJeongPark 
[x] Whenever, no rush
> Add Country Restrictions in DocStrings

- gradle/gradle-publish.gradle
- Making signing required only for builds run on CI. This is to make sure that `publishToMavenLocal` works without signing.
> skip signinig on publishing local builds

- CHANGELOG.md
- Venmo/src/main/java/com/braintreepayments/api/VenmoApi.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoApiUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- Send metadata as expected when constructing `CreateVenmoPaymentContext` - verified with Venmo backend team they are seeing this data as expected
- Base64 encode `braintree_sdk_data` in App Link URL with `_meta` key (this matches the [iOS implementation](https://github.com/braintree/braintree_ios/blob/8775b31e1e003df7a67bf1428b784eec0637364a/Sources/BraintreeVenmo/BTVenmoAppSwitchRedirectURL.swift#L58))
@jaxdesmarais 
**When do these changes need to be released?**
> Update Venmo Metadata

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalRequest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalVaultRequest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalVaultRequestUnitTest.java
- Separating out adding `payerEmail` to `PayPalVaultRequest` from the rest of the shopper insights feature branch 
- This work was previously merged into feature branch in #918 
@tdchow
> Add optional param, payerEmail, to PayPalVaultRequest 

- CHANGELOG.md
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentClient.java
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentRequest.java
- LocalPayment/src/test/java/com/braintreepayments/api/LocalPaymentClientUnitTest.java
- LocalPayment/src/test/java/com/braintreepayments/api/LocalPaymentRequestUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalCheckoutRequest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalInternalClient.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalRequest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalVaultRequest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalCheckoutRequestUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalInternalClientUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalVaultRequestUnitTest.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutInternalClient.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutRequest.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutVaultRequest.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeRequest.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalCheckoutRequestUnitTest.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalNativeCheckoutClientUnitTest.kt
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalNativeCheckoutInternalClientUnitTest.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalVaultRequestUnitTest.java
- Add `hasUserLocationConsent` param to PayPal, PayPal Native, and Local Payment modules
- Update missing changelog for Data Collector and PayPal Data Collector
> Add has user location consent param in PayPal, PayPal Native, and Local Payment modules

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/PaymentMethodNonceFormatter.java
- Demo/src/main/java/com/braintreepayments/demo/VisaCheckoutFragment.java
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutAccount.java
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutAddress.java
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutAnalytics.kt
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutClient.java
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutCreateProfileBuilderCallback.kt
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutNonce.java
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutProfileBuilderResult.kt
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutResult.kt
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutTokenizeCallback.kt
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutUserData.java
- VisaCheckout/src/test/java/com/braintreepayments/api/visacheckout/VisaCheckoutAccountUnitTest.kt
- VisaCheckout/src/test/java/com/braintreepayments/api/visacheckout/VisaCheckoutAddressUnitTest.java
- VisaCheckout/src/test/java/com/braintreepayments/api/visacheckout/VisaCheckoutAnalyticsUnitTest.kt
- VisaCheckout/src/test/java/com/braintreepayments/api/visacheckout/VisaCheckoutClientUnitTest.kt
- VisaCheckout/src/test/java/com/braintreepayments/api/visacheckout/VisaCheckoutNonceUnitTest.java
- VisaCheckout/src/test/java/com/braintreepayments/api/visacheckout/VisaCheckoutUserDataUnitTest.java
- Update Visa Checkout package name to `com.braintreepayments.api.visacheckout`
> Update Visa Checkout Package Name

- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- The ability to tokenize with `PaymentData` retrieved from a direct Google Play Services integration (calling `PaymentsClient.loadPaymentData`) [existed in v3 ](https://developer.paypal.com/braintree/docs/guides/google-pay/client-side/android/v3#direct-google-play-services-integration), but was made internal in v4. This PR adds back that functionality to allow merchants to more easily upgrade their integrations from v3 to v4. 
@sarahkoop
> Add Google Pay Direct Integration

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/PendingRequestStore.java
- Demo/src/main/java/com/braintreepayments/demo/SEPADirectDebitFragment.java
- SEPADirectDebit/src/androidTest/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitClientTest.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/CreateMandateCallback.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/CreateMandateResult.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitAnalytics.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitApi.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitClient.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitInternalTokenizeCallback.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitLauncher.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitMandateType.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitNonce.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPaymentAuthRequest.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPaymentAuthRequestCallback.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPaymentAuthRequestParams.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPaymentAuthResult.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPaymentAuthResultInfo.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPendingRequest.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitRequest.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitResult.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitTokenizeCallback.kt
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/MockSEPADirectDebitApiBuilder.java
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitAnalyticsUnitTest.kt
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitApiUnitTest.java
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitClientUnitTest.java
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitLauncherUnitTest.kt
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitNonceUnitTest.java
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPendingRequestUnitTest.kt
- Update SEPA Direct Debit package name to `com.braintreepayments.api.sepadirectdebit`
- These changes require https://github.com/braintree/browser-switch-android/pull/91 which have been published as a snapshot.
> Update SEPA Direct Debit Package Name

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalCheckoutRequest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalRequest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalVaultRequest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalCheckoutRequestUnitTest.java
- Move `userAuthenticationEmail` from `PayPalVaultRequest` to the abstract `PayPalRequest` so that it's included in `PayPalCheckoutRequest`
> Buyer Email for PayPal One Time Checkout

- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- Demo/src/main/res/layout/fragment_paypal.xml
- Demo/src/main/res/values/strings.xml
- Add text input for buyer email address in the PayPal flow
> Demo App - Add text input for setting buyer email address

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClientParams.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeOptions.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeClientUnitTest.kt
- CHANGELOG.md
- Add `appLinkReturnUri` as a parameter passed to the `BraintreeClient` constructor
- Remove unused `BraintreeClient` constructors that were marked as internal but only used in test classes
- Collapse public `BraintreeClient` constructors by using default values and `@JvmOverloads` annotation
> Add appLinkReturnUri to BraintreeClient

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalRequest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalCheckoutRequestUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalVaultRequestUnitTest.java
- Add `useAppLinkReturn` to `PayPalRequest` for Android App Link support
> Add useAppLinkReturn to PayPalRequest

- PayPal/src/main/java/com/braintreepayments/api/PayPalInternalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalInternalClientUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/MockBraintreeClientBuilder.java
- Send app link URLs to the PayPal API when `AppLinkReturnUri` is set on `BraintreeClient` and `appLinkEnabled` is set to true on the `PayPalRequest`
> Send app link URLs to PayPal API

- Demo/src/main/java/com/braintreepayments/demo/DemoActivity.java
- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- Demo/src/main/java/com/braintreepayments/demo/fragments/SettingsFragment.java
- Demo/src/main/res/values/arrays.xml
- Demo/src/main/res/values/strings.xml
- Demo/src/main/res/xml/settings.xml
- Add an option in Demo app settings for switching between deep links and app links
- The API currently fails when passing an App Link URL, which is currently expected
> Add ability to launch PayPal flows with app links

- Demo/src/main/java/com/braintreepayments/demo/DemoActivity.java
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- Demo/src/main/java/com/braintreepayments/demo/fragments/SettingsFragment.java
- Demo/src/main/res/values/strings.xml
- Demo/src/main/res/xml/settings.xml
- Add tokenization key to demo app that is associated with merchant account that is configured for new PayPal checkout experience.
- Requires settings "Tokenization Key", "PayPal Checkout Experience" and "Intent Type = Sale" to be set in demo app to launch new checkout experience from PayPal checkout flow
- Prod tokenization key does not exist for this yet, but set up demo app at allow for one to be added easily
> Add New Demo Tokenization Key for PayPal

- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalCheckoutRequest.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalCheckoutRequestUnitTest.java
- Check for empty email address - prevent passing the value to the API
- Provide a postal code in the demo app's `PayPalRequestFactory` which now seems to be required
> Handle empty email address

- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsClient.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsInfo.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/ShopperInsightsClientUnitTest.kt
- Add `isEligibleInPayPalNetwork` to `ShopperInsightsInfo` success response object
- Update logic of `isPayPalRecommended ` and `isVenmoRecommended ` to return the direct boolean from the API
> Add isEligibleInPayPalNetwork boolean to ShopperInsightsInfo

- BraintreeCore/schemas/com.braintreepayments.api.AnalyticsDatabase/5.json
- BraintreeCore/src/androidTest/java/com/braintreepayments/api/AnalyticsClientTest.java
- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsDatabase.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsEvent.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutClient.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- VisaCheckout/src/main/java/com/braintreepayments/api/VisaCheckoutClient.java
- VisaCheckout/src/test/java/com/braintreepayments/api/VisaCheckoutClientUnitTest.kt
- Send `is_vault` in `event_params` to PayPal's analytics service (FPTI)
- Add `isVaultRequest` analytics tag in `AnalyticsEvent`
- Modify AnalyticsDatabase to reflect change to `AnalyticsEvent`
- @richherrera
> Send `is_vault` FPTI tag

- PayPal/src/main/java/com/braintreepayments/api/PayPalInternalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalInternalClientUnitTest.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutInternalClient.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalNativeCheckoutInternalClientUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/Fixtures.kt
- Update PayPalInternalClient to set Client Metadata ID equal to Pairing ID internally to gain feature parity with iOS 
@sshropshire
> Update PayPalInternalClient to use Pairing ID as Client Metadata ID

- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- Add `payPalContextId` to analytics before launching browser switch based on token existing in URL from API response
@sarahkoop
> Update `payPalContextId` before launching browser

- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentLauncher.kt
- LocalPayment/src/test/java/com/braintreepayments/api/localpayment/LocalPaymentLauncherUnitTest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalLauncher.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalLauncherUnitTest.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitLauncher.kt
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitLauncherUnitTest.kt
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoLauncher.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoLauncherUnitTest.kt
- Update `browserSwitchClient` `parseResult()` to `completeRequest()` which was renamed in the latest v3 version of Browser Switch
> Browser switch updates

- CHANGELOG.md
- Quick chore to update timestamps via `git log -1 --format=%ai "$VERSION"` command for each version that didn't have a timestamp
- Not sure if this will easily merge into `v5`, if it becomes a headache we can just close it
@sshropshire
> Update CHANGELOG with Missing Timestamps

- Demo/src/main/res/layout/fragment_main.xml
- Fix demo app fragment layout that was introduced by a merge conflict
Before:
After:
> Fix demo app fragment layout

- CHANGELOG.md
- ThreeDSecure/src/main/AndroidManifest.xml
- ThreeDSecure/src/main/res/values/themes.xml
* Fix issue that causes a black screen to display after successful 3DS validation
* Make `ThreeDSecureActivity` transparency explicit via Activity theme 
https://github.com/braintree/braintree_android/assets/58225613/0e4e2967-f19b-49c5-bb2a-e0077cdcf738
https://github.com/braintree/braintree_android/assets/58225613/fa3dc5e6-3bf5-411d-9f41-60ca4dbe1864
@sshropshire
> Fix 3DS Black Screen Bug on Android 14

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalAccountNonce.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutAccountNonce.java
- The following `PayPalAccountNonce` and `PayPalNativeCheckoutAccountNonce` properties are annotated as `@NonNull` in Java:
- `firstName`
- `lastName`
- `phone`
- `payerId`
- `@NonNull` is not strictly enforced in Java, but it is strictly enforced on the Kotlin side
- We do initialize these values to `null` [here](https://github.com/braintree/braintree_android/blob/main/PayPal/src/main/java/com/braintreepayments/api/PayPalAccountNonce.java#L79) in `PayPalAccountNonce.java` and [here](https://github.com/braintree/braintree_android/blob/7c950a2a3c6483272fa5a5abe99740a8f7c21157/PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutAccountNonce.java#L79) in `PayPalNativeCheckoutAccountNonce.java`
- This causes a crash in Kotlin that has been reported by our …
> Initialize PayPalAccountNonce Values into Empty Strings Instead of `null`

- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- Demo/src/main/res/values/strings.xml
- Demo/src/main/res/xml/settings.xml
- Add Demo app Settings option to enable PayPal Pay Later
~- [] Added a changelog entry~
@sshropshire
> Add Pay Later Setting to Demo App

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/CardinalClient.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureActivity.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/CardinalClientUnitTest.kt
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureActivityUnitTest.java
- This PR extracts Cardinal cleanup functionality into it's own `CardinalClient` method
- Calling `CardinalClient.cleanup()` in `ThreeDSecureActivity` gives the Cardinal SDK enough time to finish it's async method invocations before injecting the ProgressDialog into the merchant UI
- Potential fix for #982 
- @sshropshire
> Call Cardinal Cleanup from ThreeDSecureActivity

- BraintreeCore/src/main/java/com/braintreepayments/api/core/UserCanceledException.kt
- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/googlepay/GooglePayActivityResultContract.java
- GooglePay/src/test/java/com/braintreepayments/api/googlepay/GooglePayActivityResultContractUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.java
- Remove isExplicitCancelation since UserCanceledException is always an explicit cancellation
> Remove isExplicitCancelation

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalCreditFinancing.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalCreditFinancingUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/testutils/Fixtures.kt
- Fix issue that causes a JSON parsing error when Pay Later is selected during checkout.
- Original v4 PR: https://github.com/braintree/braintree_android/pull/1059
> Fix PayPal Pay Later Parsing Error

- Demo/build.gradle
- Remove `release` build type from the demo module to fix a build issue with Retrofit and R8
> Remove the Release build type from the demo 

- .github/workflows/release.yml
- .github/workflows/temp_release.yml
- Add Setup Java steps to release workflow
- Add Temp Release Workflow for running `bump_version` and `create_github_release` jobs for `5.0.0-beta1` release. This workflow will be removed once it runs.
> Add Java Setup to all release jobs

- gradle/gradle-publish.gradle
- Remove generating and publishing of javadoc artifacts since Dokka is used for reference docs
> Remove javadocs Artifacts

- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- Demo/src/main/res/xml/settings.xml
- Add a new Enable PayPal App Switch checkbox to the settings
NOTE: Displaying an error message if the email is not configured will be added in a separate PR. (DTMOBILES-923)
- @richherrera
> Add App Switch settings to Demo App

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- Demo/src/main/res/values/arrays.xml
- Demo/src/main/res/values/strings.xml
- Demo/src/main/res/xml/settings.xml
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalRequest.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalVaultRequestUnitTest.java
- Remove `appLinkEnabled` from PayPalRequest - app link is now required for PayPal
> Remove appLinkEnabled property

- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/GraphQLConstants.kt
- CHANGELOG.md
- 3D Secure: remove token/unique ID from path
- GraphQL: remove reliance on `operationName` since this is only present for card, causing us not to send the correct path for the Venmo flow
- Both endpoints sending as expected have been verified in FPTI and via breakpoints, additionally all endpoint have been checked to ensure we are sending the expected paths now
- iOS PR: https://github.com/braintree/braintree_ios/pull/1375
> Update 3DS and GraphQL Endpoint Sent to FPTI (v5)

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalCheckoutRequest.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalRequest.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalVaultRequest.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalCheckoutRequestUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalVaultRequestUnitTest.java
- [DTMOBILES-891] Pass `AppLinkReturnUri` as a parameter to create `PayPalVaultRequest` object.
- Previous PR https://github.com/braintree/braintree_android/pull/1083
- @richherrera
> [App Switch] Pass `AppLinkReturnUri` to  `PayPalVaultRequest`

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsClientUnitTest.kt
JIRA DTMOBILES-893
- Match iOS analytics by dropping `android.` prefix from each analytic event name
- (Note: The `platform` metadata tag should be used instead to distinguish `iOS` from `Android` events)
- This lets us more easily query & analyze our metrics cross-platform
@scannillo
> Drop `android.` analytic name prefix to match iOS

- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- Demo/src/main/res/values/strings.xml
- Demo/src/main/res/xml/settings.xml
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalBillingCycle.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalRecurringBillingDetails.kt
- Add a setting in the demo app to send RBA Metadata in the PayPal Vault Request
- Update property doc strings to match iOS
> Add RBA Metadata request in the demo app and update doc strings

- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- When `Enable PayPal App Switch `checkbox is enabled, display an error message if email is not set
- @richherrera
> [App Switch] Add Toast when email is not set

- build.gradle
- v4.9.0+_MIGRATION_GUIDE.md
- v4_MIGRATION_GUIDE.md
- Update credentials used to access Cardinal SDK through Cardinal Commerce's JFrog Repository.
- PR for `v4`: https://github.com/braintree/braintree_android/pull/1103
@sshropshire
> [5.x] Update JFrog Reference Token

- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeClient.kt
- I was poking around FPTI when I noticed that one of the endpoint strings was missing the preceding slash `/`
This fix also lets us aggregate with iOS metrics
- ~Relevant test coverage~
@scannillo
> Fixup - add missing slash to FPTI `endpoint` tag for `v1/config` URL

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/DemoActivity.java
- ThreeDSecure/src/main/res/values/themes.xml
- build.gradle
- This PR adjusts the bounds of the Demo app to support edge-to-edge displays (the default in Android 15)
- This PR also effectively hides the action bar title for the `ThreeDSecureActivity` that encapsulates interaction with the Cardinal SDK
- @sshropshire
> Support Android 15 Edge-to-Edge Display And Fix 3DS Activity Bug

- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentNonce.kt
- LocalPayment/src/test/java/com/braintreepayments/api/localpayment/LocalPaymentNonceUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/testutils/Fixtures.kt
- `JSONException("givenName is null")` was getting thrown in the demo app since the response didn't contain a givenName.
- Insetead of throwing an exception, the non-null fields are set to an empty string.
> Remove throwing exceptions in LocalPaymentNonce when fields are missing

- BraintreeCore/src/androidTest/java/com/braintreepayments/api/core/BraintreeHttpClientTest.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeGraphQLClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeHttpClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ConfigurationLoader.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ConfigurationLoaderCallback.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ConfigurationLoaderResponse.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeGraphQLClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeHttpClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/ConfigurationLoaderUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/MockkConfigurationLoaderBuilder.kt
- SharedUtils/build.gradle
- SharedUtils/src/main/java/com/braintreepayments/api/sharedutils/HttpClient.java
- SharedUtils/src/main/java/com/braintreepayments/api/sharedutils/Scheduler.java
- SharedUtils/src/main/java/com/braintreepayments/api/sharedutils/ThreadScheduler.java
- SharedUtils/src/test/java/com/braintreepayments/api/sharedutils/HttpClientUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/testutils/MockThreadScheduler.java
**Note:** This PR is Part 4 in a series of refactoring PRs to eliminate `ConfigurationLoader` race conditions.
Previous PR: [#1129 [Fix ConfigurationLoader] Improve ConfigurationCache Encapsulation](https://github.com/braintree/braintree_android/pull/1129)
- This PR moves multi-threading logic into `ConfigurationLoader` to guard against race conditions related to `ConfigurationCache` access
- We create a background thread to perform synchronous HTTP requests and write to the cache in one atomic cycle
- Internally we use a single-thread thread pool to behave as a serial dispatch queue
- Only one request for `Configuration` is processed at a time. Subsequent requests are blocked until the currently active request finishes
- This results in a single HTTP config request that is cached on …
> [Fix Configuration Loader] Prevent Race Condition

- BraintreeCore/src/main/java/com/braintreepayments/api/core/DeviceInspector.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/DeviceInspectorUnitTest.kt
- Update the logic for the `isSimulator` analytics param - the logic was grabbed from this flutter plugin: https://github.com/fluttercommunity/plus_plugins/blob/bfcd3e19cb457178c5f69c5cf146a8fd8b2dec44/packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt#L110-L125
> Fix isSimulator analytics param

- AmericanExpress/src/main/java/com/braintreepayments/api/americanexpress/AmericanExpressRewardsBalance.kt
- BraintreeCore/src/androidTest/java/com/braintreepayments/api/core/AnalyticsClientTest.kt
- Card/src/main/java/com/braintreepayments/api/card/Card.kt
- Card/src/main/java/com/braintreepayments/api/card/CardClient.kt
- GooglePay/src/main/java/com/braintreepayments/api/googlepay/GooglePayPaymentAuthRequest.kt
- GooglePay/src/main/java/com/braintreepayments/api/googlepay/GooglePayRequest.kt
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentAuthRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalPaymentAuthRequest.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPaymentAuthRequest.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitRequest.kt
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecurePaymentAuthRequest.kt
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureRequest.kt
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoPaymentAuthRequest.kt
- Add doc strings noting that `requestParams` are internal so that they can be made internal when we have completed Kotlin unit test conversion
- Add JvmOverloads annotations to public request objects
- Fix some broken integration tests
@sarahkoop
> JvmOverloads and Internal Docs Cleanup

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalBillingPricing.kt
- End to end testing revealed that there are cases where amount is not required for RBA metadata in the `BTPayPalBillingPricing` - updated and tested that this can be omitted without error
@jaxdesmarais
> [QL] Make Amount Optional in `PayPalBillingPricing`

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/LocalPaymentFragment.java
- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- Demo/src/main/java/com/braintreepayments/demo/SEPADirectDebitFragment.java
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentAuthResult.kt
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentClient.kt
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentLauncher.kt
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentPendingRequest.kt
- LocalPayment/src/test/java/com/braintreepayments/api/localpayment/LocalPaymentLauncherUnitTest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalLauncher.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalPaymentAuthResult.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalPendingRequest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalLauncherUnitTest.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitClient.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitLauncher.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPaymentAuthResult.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPendingRequest.kt
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitLauncherUnitTest.kt
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoLauncher.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoLauncherUnitTest.kt
- v5_MIGRATION_GUIDE.md
- Rename `handleReturnToAppFromBrowser()` to `handleReturnToApp()` in the PayPal, SEPA, and LocalPayment modules
> Rename handleReturnToAppFromBrowser to handleReturnToApp

- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalBillingCycle.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalVaultRequestUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/testutils/Fixtures.kt
- End to end testing revealed that there are cases where `billing_frequency` and `billing_frequency_unit` are not required for `unscheduled` cases for RBA metadata - updated and tested that these fields can be omitted without error when the `recurringBillingPlanType` is `.unscheduled` and the `pricingModel` is `.autoReload` per the test case
- Updated docstrings
> [QL] Update `interval` and `intervalCount`

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEvent.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeClient.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeClientUnitTest.kt
- SharedUtils/src/main/java/com/braintreepayments/api/sharedutils/Time.kt
- There was an issue where the timestamps sent with analytic events were not accurate due to the timestamp being generated inside of a callback. This change generates the timestamp right when `sendAnalyticsEvent()` is called.
> Fix analytic event timestamps

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalVaultRequest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalVaultRequestUnitTest.java
- Fix the `os_version` so it’s sent as a String instead of an integer. This is to follow the same approach as iOS.
- Fix the overwriting of `payPalVaultRequest.enablePayPalAppSwitch`. Previously, it only checked if it was a vault request, and if the PayPal app was installed, the value was being overwritten, causing incorrect behavior.
* @richherrera
> Fix `os_version` and `enablePayPalAppSwitch`

- PayPal/build.gradle
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- Add new error if tokenization key is used and check authorization type in edit method
- Add warnings that authorization can only be client token with this feature
- Add unit test
@jaxdesmarais
> [QL] Add Error if Edit FI Authorization is Invalid

- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentPendingRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalPendingRequest.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitPendingRequest.kt
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoPendingRequest.kt
- Make `PendingRequest.Started` constructors public because they are required to reconstruct from stored string to pass to `handleReturnToApp`
@sarahkoop
> Fix PendingRequestConstructors

- PayPal/src/main/java/com/braintreepayments/api/paypal/vaultedit/PayPalVaultEditPendingRequest.kt
- Update `PayPalVaultEditPendingRequest.Started` constructor to be public because it is needed to reconstruct the object from the stored pending request string
@sarahkoop
> Fix `PayPalVaultEditPendingRequest.Started` constructor

- APP_LINK_SETUP.md
- v5_MIGRATION_GUIDE.md
- Add guide for setting up app links since it is now required for the PayPal flow. 
@sarahkoop
> App link setup docs

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalCheckoutRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalVaultRequest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalCheckoutRequestUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalVaultRequestUnitTest.java
- Add a new property to the `PayPalRequest` and pass it to support server-side shipping callbacks
- @richherrera
> Add Shipping Callback URL to PayPalRequest

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalInternalClientUnitTest.java
- Rename `risk_correlation_id` to `correlation_id` to match what should be passed to the gateway for Edit FI/Error Handling.
- Update unit tests
> Update CMID Property Passed to the Gateway

- CHANGELOG.md
- SharedUtils/src/main/java/com/braintreepayments/api/sharedutils/IntentExtensions.kt
- Fixing a crash caused by a call to `Intent.getParcelableExtra` on API 33.
- Suggestion on [Google Issue Tracker](https://issuetracker.google.com/issues/240585930) is to use older APIs for 33 to avoid the crash.
> @saperi22
> Update API where getParcelableExtra method is used

- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/MerchantRepository.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeClientUnitTest.kt
- GooglePay/src/main/java/com/braintreepayments/api/googlepay/GooglePayClient.kt
- GooglePay/src/test/java/com/braintreepayments/api/googlepay/GooglePayClientUnitTest.java
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentApi.kt
- LocalPayment/src/test/java/com/braintreepayments/api/localpayment/LocalPaymentApiUnitTest.java
- LocalPayment/src/test/java/com/braintreepayments/api/localpayment/LocalPaymentClientUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalInternalClientUnitTest.java
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClientUnitTest.kt
- TestUtils/src/main/java/com/braintreepayments/api/testutils/MockBraintreeClientBuilder.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureClient.kt
- ThreeDSecure/src/test/java/com/braintreepayments/api/threedsecure/ThreeDSecureClientUnitTest.java
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoApi.kt
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoClient.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoApiUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoClientUnitTest.java
- Create MerchantRepository which holds properties that were previously in BraintreeClient
- MerchantRepository singleton that keeps fields in memory, allowing any class to access its values via dependency injection
> Add MerchantRepository for holding BraintreeClient properties

- v5_MIGRATION_GUIDE.md
- Add a section to the v5 migration guide for handling CCT picture-in-picture
> Add section in the v5 migration guide for handing CCT picture-in-picture

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsUploadWorker.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsWriteToDbWorker.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ConfigurationLoader.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ConfigurationLoaderCallback.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ConfigurationLoaderResult.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/CoreAnalytics.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/SdkComponent.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/ConfigurationLoaderUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/MockkConfigurationLoaderBuilder.kt
- Created `ConfigurationLoaderResult` to make it easier to handle `ConfigurationLoaderCallback.onResult()`
- Move the fetching of configuration to `AnalyticsClient`
- Move latency analytics call to configuration loader
- Create SdkComponent for instantiating classes that require Context
> Add SdkComponent and move configuration fetch out of BraintreeClient

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ConfigurationLoader.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/ConfigurationLoaderUnitTest.kt
- Update AnalyticsClient scope from `internal` to `@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)`
> Expose AnalyticsClient to all modules

- AmericanExpress/build.gradle
- BraintreeCore/build.gradle
- CHANGELOG.md
- Card/build.gradle
- DataCollector/build.gradle
- Demo/build.gradle
- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/res/values/strings.xml
- GooglePay/build.gradle
- LocalPayment/build.gradle
- PayPal/build.gradle
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalCheckoutRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalVaultRequest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalCheckoutRequestUnitTest.java
- PayPalMessaging/build.gradle
- SEPADirectDebit/build.gradle
- SharedUtils/build.gradle
- ShopperInsights/build.gradle
- TestUtils/build.gradle
- ThreeDSecure/build.gradle
- Venmo/build.gradle
- VisaCheckout/build.gradle
- gradle/libs.versions.toml
- Changes for enabling app-switch for one time checkout flow.
- Added TestParameterInjector for parameterized unit tests. Fewer tests, more coverage.
@saperi22
> Update paypal request

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEvent.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEventParams.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ConfigurationLoader.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsClientUnitTest.kt
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoAnalytics.kt
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoClient.kt
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoLauncher.kt
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoRepository.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoClientUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoLauncherUnitTest.kt
- Add `app-switch:started` and `handle-return:started` events for the Venmo integration
- Add `url` analytics parameter for Venmo events. This value represents the `appSwitchUrl`
I also validated these changes in Lighthouse.
> Add app switch analytics calls for Venmo

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/LocalPaymentFragment.java
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentAuthRequestParams.kt
- Expose LocalPaymentAuthRequestParams for merchants
- Addresses https://github.com/braintree/braintree_android/issues/1207
> Expose paymentId

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalCheckoutRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalContactInformation.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalRequest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalCheckoutRequestUnitTest.java
Introduces support for passing recipient contact information in the `PayPalCheckoutRequest`
- A new class `PayPalContactInformation` was created to encapsulate the recipient's contact information for the order.
Properties: `recipientEmail` and`recipientPhoneNumber`
- Updated PayPalCheckoutRequest: Added a new optional property `contactInformation` of type `PayPalContactInformation`.
- The `contactInformation.recipientEmail` and `contactInformation.recipientPhoneNumber` are passed to the `create_payment_resource` endpoint as the `recipient_email`  and `international_phone` parameters when present.
**Note:** When the new parameters (recipient_email and international_phone) are included, the gateway returns an error. I will follow up with updates once I gather more information or implement …
> Add Contact Information request object

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/res/layout/fragment_paypal.xml
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalCheckoutRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalContactInformation.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalRequest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalCheckoutRequestUnitTest.java
- Add 'Add Contact Information' toggle to Single Payment Flow
| Before | After |
| -------- | ------- |
| <img width="418" alt="Screenshot 2024-11-26 at 2 30 21 p m" src="https://github.com/user-attachments/assets/f38232b5-8dd6-45d1-9c6e-1afb21c9720a"> | <img width="410" alt="Screenshot 2024-11-26 at 2 29 16 p m" src="https://github.com/user-attachments/assets/af88e4d3-c8c5-4421-b908-148fe00bbc08"> |
- @richherrera
> Add contact information toggle

- CHANGELOG.md
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClientUnitTest.kt
- Add `isPayPalAppInstalled` and `isVenmoAppInstalled`methods to `ShopperInsightsClient`
@sarahkoop
> Add `isPayPalAppInstalled` and `isVenmoAppInstalled` to Shopper Insights

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsParamRepository.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsParamRepositoryUnitTest.kt
- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClientUnitTest.kt
- Add `sessionId` parameter to `ShopperInsightsClient` and pass parameter as `session_id` analytics field
- Tested and confirmed the session ID passed to the demo app client is correctly appearing as `session_id` field in FPTI
@sarahkoop
> Add `sessionId` to `ShopperInsightsClient`

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEventParams.kt
- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- Add `url` to `APP_SWITCH_SUCCEEDED` and `APP_SWITCH_FAILED` events
- Add unit tests
@jaxdesmarais
> Add URL to PayPal App Switch Events

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/CardinalClient.kt
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureRequest.kt
- ThreeDSecure/src/test/java/com/braintreepayments/api/threedsecure/CardinalClientUnitTest.kt
- Add `ThreeDSecureRequest.requestorAppUrl` - this is a new property required by Mastercard for 3DS for out of band transactions. There was an internal request from a large merchant for exposing this field.
@jaxdesmarais
> Add `ThreeDSecureRequest.requestorAppUrl`

- CHANGELOG.md
- The `appLinkReturnUrl` entry accidentally made it under a previous release, this moves it under unreleased
- ~[ ] Tested and confirmed payment flows affected by this change are functioning as expected~
@jaxdesmarais
> Fixup CHANGELOG

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- Demo/src/main/res/layout/fragment_shopping_insights.xml
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalCheckoutRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalVaultRequest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalCheckoutRequestUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalVaultRequestUnitTest.java
Summary of changes
Add public property shopperSessionId to BTPaypalRequest. Value should be passed to both the create_payment_resource and setup_billing_agreement endpoints. Demo app should be updated enable/disable passing this value.
@stechiu 
@warmkesselj 
@jwarmkessel
> Shopper insights rp1 feature include session

- CHANGELOG.md
- Demo/src/main/AndroidManifest.xml
- Demo/src/main/java/com/braintreepayments/demo/VenmoFragment.java
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoClient.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoClientUnitTest.java
- Add deep link fallback to Venmo
- Fix demo app bug where a path was added to the app link URL
Tested Scenarios:
- App link
- Deep link when "Open supported links" is disabled
- Null deep link when "Open supported links" is disabled returns an error
> Venmo - Add deep link fallback

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
Override the apiClient metadata.sessionID if the shopper session Id exists.
@stechiu 
@warmkesselj 
@jwarmkessel
> Shopper insights rp1 feature sessionid analytics

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEvent.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEventParams.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsParamRepository.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsParamRepositoryUnitTest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClientUnitTest.kt
- Remove previous updates to pass existing `sessionId` for shopper insights
- Add new `shopper_session_id` FPTI tag to be used specifically for shopper insights and related payment flows
- Tested manually and verified `shopper_session_id` is getting to FPTI as expected
- Aligns with iOS PR: https://github.com/braintree/braintree_ios/pull/1485
@sarahkoop
> Add Shopper Session ID param

- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- Add missing path to Shopper Insights App Link URL
- Add required postal code for the demo app vault request.
Vault error:
```json
{
"error": {
"debugId": "b891a597f94c4",
"errorDetails": [
{
"description": "The specified country requires a postal code.",
"issue": "SHIPPING_POSTAL_CODE_REQUIRED"
}
],
"errorMessage": "The requested action could not be performed, semantically incorrect, or failed business validation. --- :",
"errorName": "UNPROCESSABLE_ENTITY",
"paypalHttpStatus": 422
}
}
```
> Fix Shopper Insights PayPal flow and PayPal Vault flow

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ShopperInsightsAnalytics.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClientUnitTest.kt
Refactor `sendPayPalSelectedEvent()` and `sendVenmoSelectedEvent()` to `sendSelectedEvent()`
@jwarmkessel 
@warmkesselj
> Shopper insights rp2 feature selected event button

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEvent.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEventParams.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoClientUnitTest.java
- Remove `paymentMethodsDisplayed` - no longer needed for v1.5 of Shopper Insights
- ~[ ] Tested and confirmed payment flows affected by this change are functioning as expected~
@jaxdesmarais
> Remove `paymentMethodsDisplayed`

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalVaultRequest.kt
- Add a conditional check to ensure that the userAuthenticationEmail is not null/empty before setting it as the payer_email
- @richherrera
> Add Payer Email to Base Parameters if not null/empty

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalLauncher.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalLauncherUnitTest.kt
- Logging the return url on starting of handleReturnToApp.
> Add return url to analytics

- Demo/src/main/res/layout/fragment_display_nonce.xml
- Demo app changes to easier selection and copying of text.
> make demo app text selectable

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AppSwitchRepository.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/GetAppSwitchUseCase.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/SetAppSwitchUseCase.kt
- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalPaymentResource.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalInternalClientUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalPaymentResourceUnitTest.java
- We were logging the app-switch analytics when a couple static checks were satisfied even if the launchPayPalApp was false from the BT gateway.
- In this PR, I'm making changes to take into consideration if launchPayPalApp is being returned true or not.
> Fix app switch vault analytics

- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- ShopperInsightsSessionId is only available in Shopper Insights flow and will be null in other flows - PayPal flow in this case.
> Send null ShopperInsightsSessionId for PayPal flows

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEventParams.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsParamRepository.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/GetReturnLinkTypeUseCase.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/GetReturnLinkUseCase.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/LinkType.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/GetReturnLinkTypeUseCaseUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/GetReturnLinkUseCaseUnitTest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoClient.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoClientUnitTest.java
- Update the logic of the `link_type` FPTI parameter - it now represents when are enabled/disabled by the user on the merchant app
- Update PayPalClient and VenmoClient to set the `linkType` property on initialization
- Separated out the app link vs deep link logic from `GetReturnLinkUseCase` into `GetReturnLinkTypeUseCase`
`GetReturnLinkTypeUseCase` - returns the type of link to be used for navigating back to the merchant app
`GetReturnLinkUseCase` - returns the actual link value (deep link or app link string value)
> link_type FPTI Parameter Updates

- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoClient.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoClientUnitTest.java
- Reset AnalyticsParamRepository at the end of the Venmo flow
> Reset AnalyticsParamRepository at the end of the Venmo flow

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsApi.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsApiUnitTest.kt
- I noticed in a recent PR we weren't actually setting the FPTI key for `error_desc` but added it to other parts of the flow - this PR adds the tag as expected
- Verified in FPTI that we now see the error description sent in our logs
- Added unit test
@jaxdesmarais
> Send `error_desc` as Expected

- .github/workflows/release.yml
- When releasing off of a branch that isn't main, the version bump should happen on the branch that we are releasing off of and not main.
> update release script

- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ButtonOrder.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ButtonType.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/PageType.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClient.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/ShopperInsightsClientV2.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClientUnitTest.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/v2/ShopperInsightsClientV2UnitTest.kt
- Add analytics calls and app installed checks to ShopperInsightsClientV2
- Clean up a few shopper insights enums
> Move existing logic to ShopperInsightsClientV2

- README.md
SSL cert expiration date has been extended to March 30, 2026
- Updated README
@stechiu
> Updated SSL cert expiration date

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureClient.kt
- ThreeDSecure/src/test/java/com/braintreepayments/api/threedsecure/ThreeDSecureClientUnitTest.kt
- Resolves https://github.com/braintree/braintree_android/issues/1321
There was a missing else block when a 3DS error is returned. The error callback was invoked along with the success callback.
> Surround the 3DS success callback when an error exists

- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/CustomerRecommendationsResult.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/CustomerSessionRequest.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/PaymentOptions.kt
- Add `CustomerRecommendationsResult` and `PaymentOptions`
- Add warning copy to `CustomerSessionRequest`'s doc string
> Add CustomerRecommendationsResult and PaymentOptions

- CHANGELOG.md
- PayPalMessaging/build.gradle
- upgrade paypal-messages from 1.0.1 to 1.0.3
@saralvasquez
> Update paypal messages version in 4.x

- CHANGELOG.md
- PayPalMessaging/build.gradle
- upgrade paypal-messages from 1.0.1 to 1.0.3
@saralvasquez
> Update paypal messages version in 5.x

- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/internal/GenerateCustomerRecommendationsApi.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/v2/internal/GenerateCustomerRecommendationsApiUnitTest.kt
- Add GenerateRecommendationsApi for the GenerateCustomerRecommendations GraphQL mutation
> Add Generate Recommendations Api

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/MockPayPalInternalClientBuilder.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/MockkPayPalInternalClientBuilder.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalInternalClientUnitTest.java
- Pass the configuration from the `PayPalClient` to the `PayPalInternalClient` - this reduces 1 configuration fetch on slower networks potential skewing latency data as we would send 3 config analytics events to FPTI. There will be a separate PR to reduce the 2 config calls to 1.
- Update unit tests
@jaxdesmarais
> Pass Configuration to `PayPalInternalClient`

- v5_MIGRATION_GUIDE.md
- Pointing to Android developer docs on when to use `onNewIntent`.
- The older suggestion of using it _only_ in case of SINGLE_TOP is misleading as there seem to be other cases when `onNewIntent()` is called and needs to be handled appropriately.
> update docs on when to use onNewIntent

- AmericanExpress/src/test/java/com/braintreepayments/api/americanexpress/AmericanExpressClientUnitTest.kt
- LocalPayment/src/test/java/com/braintreepayments/api/localpayment/LocalPaymentApiUnitTest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalInternalClientUnitTest.kt
- TestUtils/src/main/java/com/braintreepayments/api/testutils/MockkBraintreeClientBuilder.kt
- ThreeDSecure/src/test/java/com/braintreepayments/api/threedsecure/ThreeDSecureAPIUnitTest.kt
- ThreeDSecure/src/test/java/com/braintreepayments/api/threedsecure/ThreeDSecureClientUnitTest.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoApiUnitTest.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoClientUnitTest.kt
- Changed `MockkBraintreeClientBuilder` variables and functions to follow naming conventions 
- Changed function calls in Unit tests to match the changes
> @noguier
> Change var/function declarations in MockkBuilder and its references, to follow naming conventions

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalAccountNonce.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalAccountNonceUnitTest.kt
- TestUtils/src/main/java/com/braintreepayments/api/testutils/Fixtures.kt
- Add `paymentId` to `PayPalAccountNonce` - tested and verified we are getting this value as expected in sandbox
- iOS PR: https://github.com/braintree/braintree_ios/pull/1643
@jaxdesmarais
> Feature: Add Payment ID to PayPal Nonce

- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeGraphQLClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeHttpClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ConfigurationLoader.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeGraphQLClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeHttpClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/ConfigurationLoaderUnitTest.kt
- SharedUtils/src/main/java/com/braintreepayments/api/sharedutils/HttpClient.kt
- SharedUtils/src/main/java/com/braintreepayments/api/sharedutils/Method.kt
- SharedUtils/src/main/java/com/braintreepayments/api/sharedutils/OkHttpRequest.kt
- SharedUtils/src/test/java/com/braintreepayments/api/sharedutils/HttpClientUnitTest.kt
- SharedUtils/src/test/java/com/braintreepayments/api/sharedutils/OkHttpSynchronousHttpClientTest.kt
- Update HttpClient to call OkHttpSynchronusHttpClient
- Update BraintreeGraphQLClient and BraintreeHttpClient to assemble `OkHttpRequest`s
> Update HttpClient to call OkHttpSynchronusHttpClient and update BraintreeGraphQLClient andBraintreeHttpClient

- build.gradle
- gradle/libs.versions.toml
- Remove the stale `gradle-nexus-staging-plugin`
> Remove stale gradle-nexus-staging-plugin dependency
