braintree/braintree_android

- DEVELOPMENT.md
- Updated development notes to have a consistent with the readme file
> Update development notes

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/PreferredPaymentMethodsFragment.java
- Demo/src/main/java/com/braintreepayments/demo/VenmoFragment.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoAuthorizeAccountCallback.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoRequest.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoTokenizeAccountCallback.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- v4_MIGRATION_GUIDE.md
- Add `VenmoRequest` 
- Replace `VenmoClient#authorizeAccount()` with `VenmoClient#tokenizeVenmoAccount()`
- @sarahkoop
> Create VenmoRequest and Rename authorizeAccount to tokenizeVenmoAccount

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/GooglePayFragment.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayGetTokenizationParametersCallback.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayOnActivityResultCallback.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayClientUnitTest.java
- v4_MIGRATION_GUIDE.md
- Make `GooglePayClient#tokenize()` package-private
- Remove unneeded activity parameter from methods
- @sarahkoop
> Cleanup Google Pay Client

- Braintree/src/main/AndroidManifest.xml
- CHANGELOG.md
- Add Venmo to `queries` element in `AndroidManifest.xml`
- @sarahkoop
> Venmo Package Access

- Braintree/src/main/AndroidManifest.xml
- CHANGELOG.md
- ThreeDSecure/build.gradle
- Bump Cardinal version to `2.2.5-2` in `3.x` branch (`v4` to follow)
- Add PayPal to `queries` element in `AndroidManifest.xml`
- @sarahkoop
- @sshropshire
> [V3] Update Cardinal and Add PayPal to Intent Queries

- BraintreeCore/build.gradle
- BraintreeCore/src/main/AndroidManifest.xml
- CHANGELOG.md
- Demo/src/androidTest/java/com/braintreepayments/api/test/ApiClientTest.java
- Demo/src/androidTest/java/com/braintreepayments/api/test/ApiClientUnitTest.java
- ThreeDSecure/build.gradle
- Venmo/src/main/AndroidManifest.xml
- build.gradle
- Bump Cardinal version to `2.2.5-2`
- Add Venmo and PayPal apps to `queries` element in `AndroidManifest.xml`
- Bump `browser-switch` to `2.0.0-beta2`
- @sarahkoop
- @sshropshire
> [V4] Update Cardinal and Fix Venmo Bug

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/GooglePayFragment.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayRequestPaymentCallback.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayClientUnitTest.java
- v4_MIGRATION_GUIDE.md
- Addresses feedback from #343 
- Remove unnecessary parameter from `GooglePayRequestPaymentCallback`
- Fix migration guide errors
- @sarahkoop
> Address Integration Feedback

- BraintreeCore/src/androidTest/java/com/braintreepayments/api/BraintreeClientTest.java
- BraintreeCore/src/androidTest/java/com/braintreepayments/api/BraintreeGraphQLHttpClientTest.java
- BraintreeCore/src/androidTest/java/com/braintreepayments/api/PaymentMethodTest.java
- BraintreeCore/src/androidTest/java/com/braintreepayments/api/TokenizationClientTest.java
- BraintreeDataCollector/src/androidTest/java/com/braintreepayments/api/DataCollectorTest.java
- Card/src/androidTest/java/com/braintreepayments/api/CardClientTest.java
- LocalPayment/src/androidTest/java/com/braintreepayments/api/LocalPaymentClientTest.java
- ThreeDSecure/src/androidTest/java/com/braintreepayments/api/ThreeDSecureClientTest.java
- ThreeDSecure/src/androidTest/java/com/braintreepayments/api/ThreeDSecureVerificationTest.java
- UnionPay/src/androidTest/java/com/braintreepayments/api/UnionPayClientTest.java
- Fix failing integration tests from (#350) 
- @sarahkoop
> Fix Integration Tests

- Demo/build.gradle
- Demo/src/androidTest/java/com/braintreepayments/demo/test/CardTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/ThreeDSecureCardinalTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/ThreeDSecureVerificationTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/utilities/TestHelper.java
- Demo/src/main/java/com/braintreepayments/demo/AutofillHelper.java
- Demo/src/main/java/com/braintreepayments/demo/CardFragment.java
- Demo/src/main/res/layout/fragment_card.xml
- Demo/src/main/res/values/strings.xml
- Add autofill button to `CardFragment`
- Upgrade demo app to use the latest `card-form`
- @sarahkoop
> Add Card Autofill to Demo App

- BraintreeCore/build.gradle
- CHANGELOG.md
- Bump `browser-switch` to `2.0.0-beta3`
- @sarahkoop
- @sshropshire
> Update BrowserSwitch Version

- BraintreeCore/src/main/java/com/braintreepayments/api/Authorization.java
- BraintreeCore/src/main/java/com/braintreepayments/api/PaymentMethodClient.java
- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/BraintreeWalletConstants.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalCreditFinancing.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalCreditFinancingAmount.java
- UnionPay/src/main/java/com/braintreepayments/api/UnionPayCapabilities.java
- Make additional methods only used internally or by Drop-in package-private
- @sarahkoop
> Make Additional Methods Package-Private

- CHANGELOG.md
- Card/src/main/java/com/braintreepayments/api/BaseCard.java
- Card/src/main/java/com/braintreepayments/api/Card.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayCardNonce.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayIsReadyToPayCallback.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayRequest.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayInternalClientUnitTest.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayRequestUnitTest.java
- GooglePay/src/test/java/com/braintreepayments/api/MockGooglePayInternalClientBuilder.java
- UnionPay/src/main/java/com/braintreepayments/api/UnionPayCard.java
- Add getters to data classes to improve support for Kotlin synthesized properties
- Replace Boxed types with primitives where possible
- @sarahkoop
- @sshropshire
> Add Getters to Data Classes

- CHANGELOG.md
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoRequest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- Add `displayName` property to `VenmoRequest`
- @sarahkoop
- @sshropshire
> Add displayName to VenmoContext creation

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/PreferredPaymentMethodsFragment.java
- Demo/src/main/java/com/braintreepayments/demo/VenmoFragment.java
- TestUtils/src/main/java/com/braintreepayments/api/Fixtures.kt
- Venmo/src/main/java/com/braintreepayments/api/VenmoAccountNonce.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoPaymentMethodUsage.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoRequest.java
- Venmo/src/main/java/com/braintreepayments/api/VenmoSharedPrefsWriter.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoAccountNonceUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoClientUnitTest.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoRequestUnitTest.java
- v4_MIGRATION_GUIDE.md
- Use payment context in Venmo flow
- @sarahkoop
- @sshropshire
> Venmo Payment Context

- BraintreeCore/build.gradle
- CHANGELOG.md
- Bump `browser-switch` to `2.0.0`
- @sarahkoop
> Use browser-switch 2.0.0

- CHANGELOG.md
- ThreeDSecure/build.gradle
- build.gradle
- v4_MIGRATION_GUIDE.md
- Bump Cardinal version to `2.2.5-3`
- Update Cardinal credentials in demo project and migration guide
- @sarahkoop
> Update Cardinal Credentials and Bump to 2.2.5-3

- BraintreeCore/build.gradle
- CHANGELOG.md
- Bump `browser-switch` to `2.0.1` (fixes #409)
- @sestevens
- @sshropshire
> Update BrowserSwitch to 2.0.1

- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsDatabase.java
- CHANGELOG.md
- ThreeDSecure/build.gradle
- Bump Cardinal version to `2.2.5-4`
- @sarahkoop 
- @sshropshire
> Upgrade Cardinal Version to 2.2.5-4

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureRequest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureRequestUnitTest.java
-  Add `cardAdd` to `ThreeDSecureRequest`
- @kate-paypal 
- @sarahkoop
> Add `cardAdd` to `ThreeDSecureRequest`

- CHANGELOG.md
- Rakefile
- v4_MIGRATION_GUIDE.md
- Add new SamsungPay features to CHANGELOG.
- Add `:SamsungPay` module to release script.
- @sshropshire
> Samsung Pay for Release

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureRequest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureRequestUnitTest.java
- Fix issue that causes `ThreeDSecureRequest` to throw a NPE when parceling
- Ref: https://stackoverflow.com/a/29996180
- @sshropshire
> Fix ThreeDSecureRequest Parcel Error

- Braintree/src/main/java/com/braintreepayments/api/Venmo.java
- Braintree/src/test/java/com/braintreepayments/api/VenmoUnitTest.java
- CHANGELOG.md
- Core/build.gradle
- Core/src/main/java/com/braintreepayments/api/internal/CertificateHelper.java
- Core/src/main/java/com/braintreepayments/api/internal/SignatureVerification.java
- Core/src/test/java/com/braintreepayments/api/internal/SignatureVerificationUnitTest.java
- PayPalOneTouch/src/main/java/com/paypal/android/sdk/onetouch/core/sdk/AppSwitchHelper.java
- Fix issue where Venmo app is not detected on Android 12 devices
- Update signature verification encoded signatures for PayPal - app switch doesn't happen anymore, but updating for any potential future use cases
- @sarahkoop
> [V3] Update Signature Verification

- BraintreeDataCollector/src/main/java/com/braintreepayments/api/PayPalDataCollector.java
- BraintreeDataCollector/src/test/java/com/braintreepayments/api/PayPalDataCollectorUnitTest.java
- CHANGELOG.md
- Fix memory leak from `PayPalDataCollector` (fixes #419)
- @sarahkoop
> Fix Memory Leak

- CHANGELOG.md
- Add missing `3.x` versions to CHANGELOG for better transparency
> Add Missing 3.x Versions to CHANGELOG

- CHANGELOG.md
- ThreeDSecure/build.gradle
- Bump Cardinal version to latest `2.2.5-4`
> 3.x Bump Cardinal Version

- BraintreeCore/build.gradle
- CHANGELOG.md
- ThreeDSecure/src/androidTest/java/com/braintreepayments/api/ThreeDSecureClientTest.java
- ThreeDSecure/src/androidTest/java/com/braintreepayments/api/ThreeDSecureVerificationTest.java
- Revert Work Manager and Room dependencies to keep Java 7 support.
- @sarahkoop
- @sshropshire
> Revert Work Manager and Room Dependencies

- BraintreeCore/src/main/java/com/braintreepayments/api/DeviceInspector.java
- BraintreeCore/src/main/java/com/braintreepayments/api/DeviceMetadata.java
- BraintreeCore/src/test/java/com/braintreepayments/api/AnalyticsClientUnitTest.java
- BraintreeCore/src/test/java/com/braintreepayments/api/DeviceInspectorUnitTest.java
- Remove unecessary checks for the device being rooted.
> Remove Checks for Device Being Rooted

- Braintree/src/main/java/com/braintreepayments/api/PayPal.java
- Braintree/src/main/java/com/braintreepayments/api/models/PayPalRequest.java
- Braintree/src/test/java/com/braintreepayments/api/PayPalRequestUnitTest.java
- Braintree/src/test/java/com/braintreepayments/api/PayPalUnitTest.java
- CHANGELOG.md
- Add `shouldRequestBillingAgreement` to `PayPalRequest`
> Paypal Checkout with Vault

- Demo/src/main/java/com/braintreepayments/demo/MainFragment.java
- Move button member variables in demo app to avoid memory leak in SEPA flow on demo app
- @jaxdesmarais 
- @sarahkoop
> Fix Demo App Memory Leak in SEPA Flow

- BraintreeDataCollector/src/androidTest/java/com/braintreepayments/api/PayPalDataCollectorTest.java
- BraintreeDataCollector/src/main/java/com/braintreepayments/api/DataCollector.java
- BraintreeDataCollector/src/main/java/com/braintreepayments/api/PayPalDataCollector.java
- BraintreeDataCollector/src/test/java/com/braintreepayments/api/DataCollectorUnitTest.java
- BraintreeDataCollector/src/test/java/com/braintreepayments/api/PayPalDataCollectorUnitTest.java
- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentClient.java
- LocalPayment/src/test/java/com/braintreepayments/api/LocalPaymentClientUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalAccount.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalInternalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalInternalClientUnitTest.java
- Use configuration environment to set Magnes environment correctly
- @jaxdesmarais 
- @sarahkoop
> Set Magnes Environment Based on Config

- Rakefile
- This PR cleans up the Rakefile `release_braintree` task to make it easier to maintain
> Format release_braintree Rakefile Task

- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutClient.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutListener.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutNonce.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutRequest.java
- Add `tokenize()` method to `BTPayPalNativeCheckoutClient`
- Create `BTPayPalNativeCheckoutNonce`
- Create `BTPayPalNativeCheckoutRequest`
- @mattwylder
- @sarahkoop 
- @sshropshire
> Create NXO Data Models

- PayPalNativeCheckout/build.gradle
- SEPADirectDebit/build.gradle
- We need to explicitly tell our deployment plugin that we wish to skip the staging portion of deployment for SNAPSHOT builds.
- @sshropshire
> Fix Snapshots

- Demo/src/androidTest/java/com/braintreepayments/api/test/ApiClientTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/CardTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/PayPalBrowserSwitchTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/ThreeDSecureCardinalTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/ThreeDSecureVerificationTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/VenmoClientTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/utilities/TestHelper.java
- Demo/src/main/java/com/braintreepayments/demo/ClientTokenRequest.java
- Demo/src/main/java/com/braintreepayments/demo/CreateTransactionFragment.java
- Demo/src/main/java/com/braintreepayments/demo/DemoActivity.java
- Demo/src/main/java/com/braintreepayments/demo/DisplayNonceFragment.java
- Demo/src/main/java/com/braintreepayments/demo/Merchant.java
- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- Demo/src/main/java/com/braintreepayments/demo/RandomDollarAmount.java
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- Demo/src/main/java/com/braintreepayments/demo/TransactionRequest.java
- Demo/src/main/java/com/braintreepayments/demo/internal/ApiClient.java
- Demo/src/main/java/com/braintreepayments/demo/models/ClientToken.java
- Demo/src/main/res/navigation/nav_graph.xml
- Demo/src/main/res/values/arrays.xml
- Demo/src/main/res/values/strings.xml
- This PR re-enables testing for the Mock PayPal flow to fix integration test errors.
- There are no SDK changes in this PR, only the Demo app needed changes.
- @sshropshire
> Add Mock PayPal ENV

- BraintreeCore/src/androidTest/java/com/braintreepayments/api/AnalyticsClientTest.java
- BraintreeCore/src/androidTest/java/com/braintreepayments/api/ApiClientTest.java
- BraintreeCore/src/androidTest/java/com/braintreepayments/api/BraintreeClientTest.java
- BraintreeDataCollector/src/androidTest/java/com/braintreepayments/api/DataCollectorTest.java
- Card/src/androidTest/java/com/braintreepayments/api/CardClientTest.java
- Demo/src/androidTest/java/com/braintreepayments/api/test/ApiClientTest.java
- LocalPayment/src/androidTest/java/com/braintreepayments/api/LocalPaymentClientTest.java
- ThreeDSecure/src/androidTest/AndroidManifest.xml
- Remove need to launch an Activity from the module specific integration tests.
- Disable single PayPal OTC test for now.
- @sshropshire
> Integration Test Cleanup

- v4.9.0+_MIGRATION_GUIDE.md
- Replace `DataCollector` migration guide references with `PayPalDataCollector`
- @sshropshire
> Update PayPalDataCollector Docs

- CHANGELOG.md
- build.gradle
- Bump `browser-switch` version to `2.3.1`
- @mattwylder
- @sshropshire
> Bump Browser Switch Version

- Demo/src/androidTest/java/com/braintreepayments/demo/test/ThreeDSecureVerificationTest.java
- ThreeDSecure/src/androidTest/java/com/braintreepayments/api/ThreeDSecureClientTest.java
- ThreeDSecure/src/androidTest/java/com/braintreepayments/api/ThreeDSecureVerificationTest.java
- Skip 3DS v1 tests for deprecated cards.
- @jaxdesmarais 
- @sshropshire
> YOLO Skip 3D Secure v1 Tests

- Demo/src/androidTest/java/com/braintreepayments/demo/test/ThreeDSecureCardinalTest.java
- Add test cases in cardinal for V2 cards
- @kgangineni @jaxdesmarais
> add Card V2 Integration tests for cardinal

- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- README.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureClient.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureClientUnitTest.java
- Update broken docs links in exceptions to point to new PayPal docs site
- Update docs link in README to point to new PayPal docs site
> Update Broken Docs Links in Exceptions

- BraintreeCore/src/main/java/com/braintreepayments/api/Configuration.kt
- There were a few properties / methods that should have been public initially
- @sshropshire
> Fix Migration Typos

- BraintreeCore/build.gradle
- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsBaseWorker.java
- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsUploadWorker.java
- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsWriteToDbWorker.java
- BraintreeCore/src/main/java/com/braintreepayments/api/PreferredPaymentMethodsCallback.java
- BraintreeCore/src/main/java/com/braintreepayments/api/PreferredPaymentMethodsClient.java
- BraintreeCore/src/main/java/com/braintreepayments/api/PreferredPaymentMethodsResult.java
- VisaCheckout/build.gradle
- build.gradle
- Add Dokka HTML `@hide` support for Java classes
- Suppress documentation for `PreferredPaymentMethod` classes
- Suppress documentation for `visa-checkout` module
- @sshropshire
> Suppress Preferred Payment Methods and Other Classes

- BraintreeCore/src/main/java/com/braintreepayments/api/ApiClient.kt
-  remove `if not null` for `also`
- refactor to remove repeated logic.
- @jcnoriega
> Refactor ApiClient Internally

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- BraintreeDataCollector/src/main/java/com/braintreepayments/api/DataCollector.java
- BraintreeDataCollector/src/test/java/com/braintreepayments/api/DataCollectorUnitTest.java
- fix memory leak in "DataCollector" 
- @KunJeongPark 
- @sshropshire
> Fix memory issue with DataCollector class

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClientParams.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeOptions.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/PostalAddressParser.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/PreferredPaymentMethodsCallback.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/PreferredPaymentMethodsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/PreferredPaymentMethodsResult.kt
- Updating some access modifiers to match Java semantics
- Adding `@suppress` annotations to prevent docs generation for some library protected classes
- @sshropshire
> Pre 4.26.2 Kotlin Clean Up

- AmericanExpress/build.gradle
- BraintreeCore/build.gradle
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeError.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/ErrorWithResponse.kt
- BraintreeDataCollector/build.gradle
- Card/build.gradle
- GooglePay/build.gradle
- LocalPayment/build.gradle
- PayPal/build.gradle
- PayPalDataCollector/build.gradle
- PayPalNativeCheckout/build.gradle
- SEPADirectDebit/build.gradle
- SamsungPay/build.gradle
- SharedUtils/build.gradle
- TestUtils/build.gradle
- ThreeDSecure/build.gradle
- UnionPay/build.gradle
- Venmo/build.gradle
- VisaCheckout/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Update Android Gradle Plugin
- Tweak Merchant Facing API to improve Kotlin / Java Interop
- Update Kotlin Version to fix build error
- @sshropshire
> Prepare for 4.28.0 Deployment

- CHANGELOG.md
- PayPalNativeCheckout/build.gradle
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutClient.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalNativeCheckoutClientUnitTest.java
- Reverting android changes to fix p0
-
> Reverting native changes

- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureRequest.java
- Update typo in `setRequestedExemptionType()` docstring
- Issue raised in #bt-service-client-sdks
@scannillo
> Fix typo in `setRequestedExemptionType()` docstring

- CHANGELOG.md
- build.gradle
> Update Cardinal to 2.2.7-3

- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayCardNonce.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayCardNonceUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/Fixtures.kt
- Add `getBin` to `GooglePayCardNonce`
- Update test to add `getBin`
- Verified bin is returned as expected in demo app
> Add `getBin` to `GooglePayCardNonce`

- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureClient.java
- Send analytics for Cardinal initialization exceptions
> Send Analytics for Cardinal Initialization Exceptions

- CHANGELOG.md
- Venmo/src/main/java/com/braintreepayments/api/VenmoApi.java
- Venmo/src/test/java/com/braintreepayments/api/VenmoApiUnitTest.java
* Venmo
* Add missing space to Venmo `PaymentContext` GraphQL query (fixes #749)
- @sshropshire
> Venmo Fix GraphQL Typo

- CHANGELOG.md
- PayPalNativeCheckout/build.gradle
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutAccountNonce.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutClient.java
- PayPalNativeCheckout/src/main/java/com/braintreepayments/api/PayPalNativeCheckoutInternalClient.java
- PayPalNativeCheckout/src/test/java/com/braintreepayments/api/PayPalNativeCheckoutClientUnitTest.kt
- build.gradle
- Updating nxo to GA
- Adding a fix from the web fallback flow that pulls the user data from the approval data object from native checkout
-
> MXO-1160 - Nxo fix fallback from web and update nxo to GA

- CHANGELOG.md
- build.gradle
- Bump `browser-switch` version to `2.5.0`
- @sshropshire
> Browser Switch 2.5.0

- CHANGELOG.md
- PayPalNativeCheckout/build.gradle
- Buy Now Pay Later entry points
- Improved authentication flows in SCA regions
- Minor UI fixes
-
> Update mxo 1.1.0

- v4.9.0+_MIGRATION_GUIDE.md
- Add note about process kill in Migration Guide section on Manual Browser Switching
- @sshropshire
> Migration Guide: Manual Browser Switch Process Kill

- CHANGELOG.md
- build.gradle
- Bump browser switch to 2.5.1 to fix case sensitive return URL scheme bug
- @sarahkoop
> Update Browser Switch

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/CardinalClient.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureActivity.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/CardinalClientUnitTest.kt
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureActivityUnitTest.java
- build.gradle
- Update Cardinal SDK to 2.2.7-4
- @sarahkoop
> Update Cardinal to 2.2.7-4

- ThreeDSecure/src/main/java/com/braintreepayments/api/CardinalClient.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureActivity.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/ThreeDSecureActivityUnitTest.java
- Update Cardinal SDK to 2.2.7-4
- Continuation of https://github.com/braintree/braintree_android/pull/777
- @sarahkoop 
- @sshropshire
> Update Cardinal to 2.2.7-4 (Continued)

- README.md
- Add link to github pages site with full reference docs to readme
- @sarahkoop
> Add link to reference docs to README

- BraintreeCore/src/main/java/com/braintreepayments/api/Configuration.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/ConfigurationLoader.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/ConfigurationUnitTest.kt
- CHANGELOG.md
- GooglePay/proguard.pro
- TestUtils/src/main/java/com/braintreepayments/api/Fixtures.kt
- VisaCheckout/proguard.pro
- Resolve NEXT_MAJOR_VERSION notes in `Configuration`
- @sarahkoop
> Configuration Major Version Updates

- CHANGELOG.md
- build.gradle
- Bump browser switch to version that contains bug fix for ActivityNotFoundException (fixes #799)
- @sarahkoop
> Bump Browser Switch

- README.md
- update 3.x.x to unsupported
- @MaxHastingsPP
> Update 3.x.x to unsupported

- CHANGELOG.md
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayGetTokenizationParametersCallback.java
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayTokenizationParameters.kt
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayClientUnitTest.java
- Break out Google Pay changes from #857 
- Update additional Google Pay public method with single result object
- @sarahkoop
> Google Pay Public Methods Single Result

- GooglePay/src/main/java/com/braintreepayments/api/GooglePayAnalytics.kt
- GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayAnalyticsUnitTest.kt
- GooglePay/src/test/java/com/braintreepayments/api/GooglePayClientUnitTest.java
- Update Google Pay integration with FPTI analytics events
- Add additional event for cancel scenario (also updated source of truth FPTI event tracker)
- Convert GooglePayAnaltyics enum into simple object
- @sarahkoop
> Update Google Pay with FPTI Analytics

- CHANGELOG.md
- PayPalNativeCheckout/build.gradle
> Update mxo 1.2.1

- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsAnalytics.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/ShopperInsightsClientUnitTest.kt
- Add analytics events for Shopper Insights
- @saperi22
> Add analytics events

- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsClient.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/AnalyticsClientUnitTest.kt
- See equivalent PR description on iOS https://github.com/braintree/braintree_ios/pull/1175
@scannillo 
**When do these changes need to be released?**
> Drop -m suffix from `api.paypal.com` FPTI URL

- PayPal/src/main/java/com/braintreepayments/api/PayPalAnalytics.kt
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/PayPalAnalyticsUnitTest.kt
- PayPal/src/test/java/com/braintreepayments/api/PayPalClientUnitTest.java
- Update PayPal flow with FPTI analytics events
@sarahkoop
> Implement PayPal FPTI Analytics

- README.md
- build.gradle
- v5_MIGRATION_GUIDE.md
- Update README for v5 beta
- Update gradle tasks for publishing betas with format `5.0.0-beta1`
@sarahkoop
> Update README and Gradle Tasks for v5 beta

- SEPADirectDebit/src/main/java/com/braintreepayments/api/SEPADirectDebitAnalytics.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/SEPADirectDebitClient.java
- SEPADirectDebit/src/test/java/com/braintreepayments/api/SEPADirectDebitAnalyticsUnitTest.kt
- SEPADirectDebit/src/test/java/com/braintreepayments/api/SEPADirectDebitClientUnitTest.java
- Implement SEPA FPTI analytics (this includes non-conversion events that will likely be moved to events details in future PR)
- Fix incorrect failure that should be cancel result
@sarahkoop
> SEPA Direct Debit FPTI Analytics

- VisaCheckout/src/main/java/com/braintreepayments/api/VisaCheckoutAnalytics.kt
- VisaCheckout/src/main/java/com/braintreepayments/api/VisaCheckoutClient.java
- VisaCheckout/src/test/java/com/braintreepayments/api/VisaCheckoutAnalyticsUnitTest.kt
- VisaCheckout/src/test/java/com/braintreepayments/api/VisaCheckoutClientUnitTest.kt
- Add visa checkout FPTI analytics
@sarahkoop
> Update Visa Checkout FPTI Analytics

- Demo/src/main/java/com/braintreepayments/demo/PayPalMessagingFragment.kt
- PayPalMessaging/src/main/java/com/braintreepayments/api/PayPalMessagingView.kt
- Move to `setListener()` pattern used in other modules
- Remove unneeded else block 
@jaxdesmarais
> Cleanup PayPal Messaging Implementation

- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- Invoke merchant logging functions in the Shopper Insights demo
> Add Shopper Insights Merchant Logging to Demo

- Demo/src/debug/AndroidManifest.xml
- Demo/src/main/res/xml/network_security_config.xml
- Adding network config to accept user CA for debug builds.
> Add network config for Demo app

- .github/workflows/release_snapshot.yml
- Add workflow_dispatch for releasing snapshot builds
> Add workflow_dispatch for releasing snapshot builds

- PayPalDataCollector/src/androidTest/java/com/braintreepayments/api/PayPalDataCollectorTest.java
- Fix compile error in PayPalDataCollectorTest
> Fix compile error in PayPalDataCollectorTest

- Demo/src/main/AndroidManifest.xml
- Add intent filter for demo app link
> Add intent filter for demo app link

- README.md
- Added info about upgrading Braintree SDK for latest SSL certs in README
@stechiu
> Update README - Added upgrade SDK message

- BraintreeCore/schemas/com.braintreepayments.api.AnalyticsDatabase/3.json
- BraintreeCore/schemas/com.braintreepayments.api.AnalyticsDatabase/4.json
- BraintreeCore/src/androidTest/java/com/braintreepayments/api/AnalyticsClientTest.java
- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsDatabase.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/AnalyticsEvent.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- Add `venmo_installed` analytics tag in `AnalyticsEvent`
- Modify` sendEvent` to fetch isVenmoInstalled value from `DeviceInspector`
- Modify AnalyticsDatabase to reflect change to `AnalyticsEvent`
- [] Added a changelog entry
@KunJeongPark
> Add `venmo_installed` Analytics tag

- PayPalMessaging/build.gradle
- PayPalMessaging/src/main/java/com/braintreepayments/api/PayPalMessagingTextAlignment.kt
- PayPalMessaging/src/main/java/com/braintreepayments/api/PayPalMessagingView.kt
- PayPalMessaging/src/test/java/com/braintreepayments/api/PayPalMessagingTextAlignmentUnitTest.kt
Update to use develop.3 for credit messaging and update the demo app to use the updated textAlignment property.
@saperi22 
@KunJeongPark 
@jwarmkessel
> Paypal messaging feature update dependency

- CHANGELOG.md
- Update changelog for Shopper Insights module
> Add Shopper Insights to the changelog

- PayPalMessaging/build.gradle
- Bump PayPalMessages to 1.0.1
@jaxdesmarais
> Bump PayPalMessages to 1.0.1

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/BraintreeClientUnitTest.kt
- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/BraintreeClientFactory.java
- Demo/src/main/java/com/braintreepayments/demo/DemoActivity.java
- PayPal/src/main/java/com/braintreepayments/api/PayPalClient.java
- build.gradle
- Send app link url to browser switch
- @saperi22
> Pass app link to browser switch

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- ShopperInsights/src/main/java/com/braintreepayments/api/EligiblePaymentsApiRequest.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsApi.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/EligiblePaymentsApiRequestUnitTest.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/EligiblePaymentsApiUnitTest.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/ShopperInsightsClientUnitTest.kt
- Remove unneeded `XO_PRODUCTION_TOKENIZATION_KEY`
- Remove `merchantId` from `EligiblePaymentsApiRequest`
- Remove new line in `ShopperInsightsApi`
These changes are from this PR's review: https://github.com/braintree/braintree_android/pull/1023
> Shopper Insights Final Changes

- README.md
- v5_MIGRATION_GUIDE.md
- Update README & Migration guide for V5 minimum tooling requirements
- ~Relevant test coverage~
@scannillo
> Clarify Java & AGP requirements

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/MainFragment.java
- Demo/src/main/java/com/braintreepayments/demo/PayPalMessagingFragment.kt
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- Demo/src/main/res/layout/fragment_main.xml
- Demo/src/main/res/navigation/nav_graph.xml
- PayPalMessaging/src/main/java/com/braintreepayments/api/PayPalMessagingView.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/ShopperInsightsClient.kt
- Making changes to the demo app to make it work with v5 changes.
> Fixups for main merge into v5

- GooglePay/src/main/java/com/braintreepayments/api/googlepay/GooglePayPaymentAuthRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalPaymentAuthRequest.kt
- Fix copy-paste typos in AuthRequest class docstrings
@scannillo
> Fix typos in AuthRequest docstrings

- v5_MIGRATION_GUIDE.md
- Fix a few syntax issues
- Add error cases to when statements
> Final v5 migration guide changes

- Demo/src/main/java/com/braintreepayments/demo/LocalPaymentFragment.java
- Demo/src/main/java/com/braintreepayments/demo/SEPADirectDebitFragment.java
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- Demo/src/main/java/com/braintreepayments/demo/VenmoFragment.java
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentClient.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitClient.java
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoClient.java
- Add `returnUrlScheme` param to Local Payment, SEPA, and Venmo clients
Note - I was unable to find a good way to unit test these changes without refactoring how dependency injection currently works. If anyone has other ideas on how to test the returnUrlScheme field, please let me know!
> Add returnUrlScheme to feature clients

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEvent.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AppSwitchNotAvailableException.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeError.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ConfigurationException.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/ErrorWithResponse.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/InvalidArgumentException.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/UserCanceledException.kt
- GooglePay/src/test/java/com/braintreepayments/api/googlepay/GooglePayActivityResultContractUnitTest.java
- Remove unneeded open modifier on various classes and properties
- Fix a small typo in property name
> Remove unneeded open modifier

- build.gradle
- Update Browser Switch to 3.0.0-beta1
> Update Browser Switch to 3.0.0-beta1

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/CardinalClient.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureActivity.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/threedsecure/CardinalClientUnitTest.kt
- ThreeDSecure/src/test/java/com/braintreepayments/api/threedsecure/ThreeDSecureActivityUnitTest.java
- Update changes from #1048  against v5
> PR #1048 into v5

- CHANGELOG.md
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureRequest.java
- ThreeDSecure/src/test/java/com/braintreepayments/api/threedsecure/ThreeDSecureRequestUnitTest.java
- Update changes from #1044 against v5
@jaxdesmarais
> PR #1044 into v5

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEventParams.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeClient.kt
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentClient.java
- LocalPayment/src/test/java/com/braintreepayments/api/localpayment/LocalPaymentClientUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoClient.java
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoClientUnitTest.java
- Extracts all the parameters that are necessary to send in events to an object (AnalyticsEventParams)
- Original PR into main: https://github.com/braintree/braintree_android/pull/1031
> Create Analytics Event Params object

- CHANGELOG.md
- VisaCheckout/build.gradle
- v5_MIGRATION_GUIDE.md
- Disable Visa Checkout Publishing for v5
> Disable Visa Checkout Publishing for v5

- BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/GraphQLConstants.kt
- CHANGELOG.md
- Update changes from #1080 into v4
@jaxdesmarais
> PR #1080 into v4

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- Remove lingering analytic events from v4
- Slight refactor in PayPalClient - removed a few private functions that did the same for vault and checkout flows
> Remove old analytic events lingering from v4

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/vaultedit/PayPalVaultEditRequest.kt
- Add `merchantAccountId` to `PayPalVaultEditRequest`
- Update kdoc
- Suppress detekt issue that was introduced from pulling main into the feature branch
> Add merchantAccountId for Edit FI

- PayPal/src/main/java/com/braintreepayments/api/paypal/vaultedit/PayPalVaultEditResult.kt
- Add properties to `PayPalVaultEditResult.Success`
> Add PayPalVaultEditResult.Success properties

- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
[DTMOBILES-895]
- Add a toast that surfaces the BA Token as soon as we get it in the response from `setup_billing_agreement`
**Note:** These changes will be reverted before the feature release [DTMOBILES-896].
- @richherrera
> [App Switch] Surface BA Token

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEvent.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/BraintreeClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/DeviceMetadata.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/DeviceInspectorUnitTest.kt
- This PR moves `venmo_installed` property to batch params so that it doesn't have to be sent with every event.
- @sshropshire
> [5.x] Analytics – Move `venmo_installed` Property to Batch Params

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalAnalytics.kt
Named analytics for edit FI.
@jwarmkessel @KunJeongPark
> EDITFI analytics names

- AmericanExpress/build.gradle
- BraintreeCore/build.gradle
- Card/build.gradle
- DataCollector/build.gradle
- Demo/build.gradle
- Demo/src/main/res/values/styles.xml
- GooglePay/build.gradle
- LocalPayment/build.gradle
- PayPal/build.gradle
- PayPalMessaging/build.gradle
- SEPADirectDebit/build.gradle
- SharedUtils/build.gradle
- ShopperInsights/build.gradle
- TestUtils/build.gradle
- ThreeDSecure/build.gradle
- Venmo/build.gradle
- VisaCheckout/build.gradle
- build.gradle
- gradle/libs.versions.toml
- settings.gradle
- This PR adds a `libs.versions.toml` file that contains all versions, libraries, and plugins.
https://developer.android.com/build/migrate-to-catalogs#groovy
> Add Version Catalog

- Card/src/androidTest/java/com/braintreepayments/api/card/CardClientTest.java
- DataCollector/src/androidTest/java/com/braintreepayments/api/datacollector/DataCollectorTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/PayPalBrowserSwitchTest.java
- Demo/src/main/res/navigation/nav_graph.xml
- Demo/src/main/res/values/strings.xml
- LocalPayment/src/androidTest/java/com/braintreepayments/api/localpayment/LocalPaymentClientTest.java
- SharedUtils/build.gradle
- SharedUtils/src/androidTest/java/com/braintreepayments/api/sharedutils/ManifestTestActivity.java
- SharedUtils/src/androidTest/java/com/braintreepayments/api/sharedutils/MissingManifestTestActivity.java
- This PR fixes compilation errors related to integration tests.
- @sshropshire
> V5 Android 15: Fix Remaining Integration Tests

- BraintreeCore/src/main/java/com/braintreepayments/api/core/GraphQLConstants.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeGraphQLClientUnitTest.kt
- CHANGELOG.md
- Bump the GraphQL API Version based on the current date
I verified a few PayPal flows, everything is working as expected. We'll do a full regression before v5 goes GA.
> Bump GraphQL API Version

- Card/src/main/java/com/braintreepayments/api/card/BinData.kt
- Card/src/main/java/com/braintreepayments/api/card/BinType.kt
- Card/src/test/java/com/braintreepayments/api/card/BinTypeUnitTest.kt
- Ignore case when converting JSON to BinType enums
> Fix BinType crash

- Demo/build.gradle
- Demo/src/main/java/com/braintreepayments/demo/CreateTransactionFragment.java
- Demo/src/main/java/com/braintreepayments/demo/DemoApplication.java
- Demo/src/main/java/com/braintreepayments/demo/Merchant.java
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- Demo/src/main/java/com/braintreepayments/demo/internal/ApiClient.java
- Demo/src/main/java/com/braintreepayments/demo/internal/ApiClientRequestInterceptor.java
- gradle/libs.versions.toml
- Update Retrofit in the Demo app from 1.9.0 to 2.11.0
- Resolve all breaking changes
- Bump material design to 1.12.0
> Update the demo app to Retrofit 2.11.0

- BraintreeCore/src/main/java/com/braintreepayments/api/core/ErrorWithResponse.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/ErrorsWithResponseUnitTest.kt
- TestUtils/src/main/java/com/braintreepayments/api/testutils/Fixtures.kt
- Parse additional possible error messages in error responses: `errorMessage` and `developer_message`
> Improved Error Message Parsing

- CHANGELOG.md
- Update CHANGELOG
@richherrera
> [App Switch] Update CHANGELOG

- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- Revert posting BA token 
- @richherrera
> Remove BA toast from PayPal Fragment

- Demo/src/androidTest/java/com/braintreepayments/api/test/ApiClientTest.java
- Demo/src/androidTest/java/com/braintreepayments/demo/test/PayPalBrowserSwitchTest.java
- Demo/src/main/java/com/braintreepayments/demo/ClientTokenRequest.kt
- Demo/src/main/java/com/braintreepayments/demo/CreateTransactionFragment.java
- Demo/src/main/java/com/braintreepayments/demo/Merchant.java
- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- Demo/src/main/java/com/braintreepayments/demo/TransactionRequest.kt
- Demo/src/main/java/com/braintreepayments/demo/internal/ApiClient.java
- Demo/src/main/java/com/braintreepayments/demo/models/ClientToken.java
- Demo/src/main/res/values/arrays.xml
- Demo/src/main/res/values/strings.xml
- This PR makes the Demo app use the same BT sample merchant server as iOS
- This PR uses #577 as a reference
- @sshropshire
> Revert to Braintree Merchant Server

- BraintreeCore/build.gradle
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEventParams.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/BraintreeClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/PostalAddressUnitTest.kt
- Demo/src/main/java/com/braintreepayments/demo/MainFragment.kt
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- Demo/src/main/res/layout/fragment_card.xml
- Demo/src/main/res/layout/fragment_paypal.xml
- Demo/src/main/res/values/strings.xml
- Demo/src/main/res/values/styles.xml
- GooglePay/src/main/java/com/braintreepayments/api/googlepay/GooglePayActivity.kt
- GooglePay/src/test/java/com/braintreepayments/api/googlepay/GooglePayActivityResultContractUnitTest.kt
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentClient.kt
- LocalPayment/src/test/java/com/braintreepayments/api/localpayment/LocalPaymentClientUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalAccount.kt
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitClient.kt
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitClientUnitTest.java
- SharedUtils/src/main/java/com/braintreepayments/api/sharedutils/AppHelper.java
- SharedUtils/src/main/java/com/braintreepayments/api/sharedutils/IntentExtensions.kt
- SharedUtils/src/test/java/com/braintreepayments/api/sharedutils/AppHelperUnitTest.java
- TestUtils/src/main/java/com/braintreepayments/api/testutils/Assertions.java
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureActivity.kt
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureActivityResultContract.kt
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureNonce.kt
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoClient.kt
- build.gradle
- gradle/libs.versions.toml
- replace kapt with ksp
- remove unused properties and resources
- add Intent extension functions for handling deprecated functions
- address other minor warnings
> Fix lint warnings

- .github/workflows/firebase_deploy_demo.yml
- .github/workflows/release_snapshot.yml
- Update branch on firebase app distribution github action workflow 
> Firebase App Distribution Branch

- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/vaultedit/PayPalVaultEditRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/vaultedit/PayPalVaultErrorHandlingEditRequest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalInternalClientUnitTest.java
Add a property to the EditFi request obj `hasUserLocationConsent` for DataCollector to consume.
@jwarmkessel
> Edit fi v5 feature magnes location consent

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalAnalyticsUnitTest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
> Edit fi v5 feature pp analytics

- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecurePrepareLookupCallback.kt
- Make ThreeDSecurePrepareLookupCallback a functional interface for better Kotlin support
> Make ThreeDSecurePrepareLookupCallback a functional interface

- Demo/src/main/java/com/braintreepayments/demo/Settings.java
- TestUtils/src/main/java/com/braintreepayments/api/testutils/TestClientTokenBuilder.java
Updating the url endpoints for the new Heroku apps ruby server.
> Update heroku server endpoints

- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
> update json string in demo app

- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragment.kt
- Update demo app to reflect correct usage of the SI analytics methods.
@saperi22
> Update ShopperInsights demo

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- Enable app switch for one time checkout.
> One time checkout app switch changes

- Demo/src/main/java/com/braintreepayments/demo/BaseFragment.java
- Demo/src/main/java/com/braintreepayments/demo/CardFragment.java
- Demo/src/main/java/com/braintreepayments/demo/CardViewModel.kt
- Demo app fix for crash on 3DS card screen.
> Fix 3ds npe

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEvent.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEventParams.kt
- CHANGELOG.md
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalLauncher.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- Add error_desc tag to our analytics.
- Log failure message as error_desc for failed analytics logs.
> Add error description to paypal analytics

- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsApi.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsClient.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsEvent.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/AnalyticsParamRepository.kt
- BraintreeCore/src/main/java/com/braintreepayments/api/core/LinkType.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsApiUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsClientUnitTest.kt
- BraintreeCore/src/test/java/com/braintreepayments/api/core/AnalyticsParamRepositoryUnitTest.kt
- CHANGELOG.md
- Card/src/main/java/com/braintreepayments/api/card/CardClient.kt
- Card/src/test/java/com/braintreepayments/api/card/CardClientUnitTest.java
- GooglePay/src/main/java/com/braintreepayments/api/googlepay/GooglePayClient.kt
- GooglePay/src/test/java/com/braintreepayments/api/googlepay/GooglePayClientUnitTest.java
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentClient.kt
- LocalPayment/src/test/java/com/braintreepayments/api/localpayment/LocalPaymentClientUnitTest.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalClient.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalClientUnitTest.java
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalInternalClientUnitTest.java
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClientUnitTest.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoClientUnitTest.java
- Add `merchant_enabled_app_switch` and `attempted_app_switch` analytics params
- Add properties to `AnalyticsParamRepository` to hold the state of these new params
- Rename `AnalyticsParamRepository.resetSessionId()` to `AnalyticsParamRepository.reset()` as it now clears all stored properties
- Fix an issue where `PayPalClient` was not invoking `AnalyticsParamRepository.reset()`
- Update LinkType.APP_LINK value to "applink"
Example request:
``` json
{
"events": [
{
"batch_params": {
"app_id": "com.braintreepayments.demo",
"app_name": "Braintree Demo",
"c_sdk_ver": "5.8.1-SNAPSHOT",
"client_os": "Android API 35",
"comp": "braintreeclientsdk",
"device_manufacturer": "Google",
"mobile_device_model": "sdk_gphone64_arm64",
"event_source": "mobile-native",
"merchant_sdk_env": "sandbox", …
```
> Add App Switch Analytic Params

- AmericanExpress/src/main/java/com/braintreepayments/api/americanexpress/AmericanExpressClient.kt
- AmericanExpress/src/test/java/com/braintreepayments/api/americanexpress/AmericanExpressClientUnitTest.java
- CHANGELOG.md
- Card/src/main/java/com/braintreepayments/api/card/CardClient.kt
- Card/src/test/java/com/braintreepayments/api/card/CardClientUnitTest.java
- GooglePay/src/main/java/com/braintreepayments/api/googlepay/GooglePayClient.kt
- GooglePay/src/test/java/com/braintreepayments/api/googlepay/GooglePayClientUnitTest.java
- LocalPayment/src/main/java/com/braintreepayments/api/localpayment/LocalPaymentClient.kt
- LocalPayment/src/test/java/com/braintreepayments/api/localpayment/LocalPaymentClientUnitTest.java
- SEPADirectDebit/src/main/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitClient.kt
- SEPADirectDebit/src/test/java/com/braintreepayments/api/sepadirectdebit/SEPADirectDebitClientUnitTest.java
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClient.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/ShopperInsightsClientUnitTest.kt
- ThreeDSecure/src/main/java/com/braintreepayments/api/threedsecure/ThreeDSecureClient.kt
- ThreeDSecure/src/test/java/com/braintreepayments/api/threedsecure/ThreeDSecureClientUnitTest.java
- Venmo/src/main/java/com/braintreepayments/api/venmo/VenmoClient.kt
- Venmo/src/test/java/com/braintreepayments/api/venmo/VenmoClientUnitTest.java
- VisaCheckout/src/main/java/com/braintreepayments/api/visacheckout/VisaCheckoutClient.kt
- VisaCheckout/src/test/java/com/braintreepayments/api/visacheckout/VisaCheckoutClientUnitTest.kt
- Add errorDesc to existing FPTI failure events
* Tested a 3DS flow to see if error_desc is being logged into FPTI.
> Add error description to FPTI analytics for all modules

- CHANGELOG.md
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/PageType.kt
- Add `PAYMENT_METHOD_SELECTION` and `PAYMENT_METHOD_ADDITION` for Payment Ready v2
> Add new page types for Payment Ready v2

- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/CustomerSessionRequest.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/PurchaseUnit.kt
- Add CustomerSessionRequest and PurchaseUnit request objects
> Add CustomerSessionRequest and PurchaseUnit request objects

- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/CreateCustomerSessionApi.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/v2/CreateCustomerSessionApiUnitTest.kt
- Add CreateCustomerSessionApi for creating a customer session
I verified the API call with hardcoded values. A valid session ID was returned.
> Add CreateCustomerSessionApi for creating a customer session

- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- PayPal/src/main/java/com/braintreepayments/api/paypal/AmountBreakdown.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalCheckoutRequest.kt
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalRequest.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalCheckoutRequestUnitTest.java
Add AmountBreakdown, update the post body to communicate with Gateway to make sure we're getting a successful response.
@jwarmkessel @warmkesselj
> Checkout rba metadata feature gateway

- build.gradle
- Sonatype sunset OSSRH. Adding the new url for snapshot publishing.
> Set new repository url for snapshot publishing.

- CHANGELOG.md
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/CustomerRecommendations.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/CustomerRecommendationsResult.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/ShopperInsightsClientV2.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/internal/GenerateCustomerRecommendationsApi.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/v2/ShopperInsightsClientV2UnitTest.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/v2/internal/GenerateCustomerRecommendationsApiUnitTest.kt
- Added `generateCustomerRecommendations` to `ShopperInsightsClientV2`
- Moved `CustomerRecommendations` data class to new separate class from the results class
- Added a failure and success case to `CustomerRecommendationsResult`
- Unit test support for `generateCustomerRecommendations`
**Note: used Github Copilot AI tool support**
@saralvasquez
> Add generateCustomerRecommendations to ShopperInsightsClientV2

- CHANGELOG.md
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/ShopperInsightsClientV2.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/v2/ShopperInsightsClientV2UnitTest.kt
- added updateCustomerSession function to ShopperInsightsClientV2
> added updateCustomerSession function to ShopperInsightsClientV2

- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/ShopperInsightsAnalytics.kt
- ShopperInsights/src/main/java/com/braintreepayments/api/shopperinsights/v2/ShopperInsightsClientV2.kt
- ShopperInsights/src/test/java/com/braintreepayments/api/shopperinsights/v2/ShopperInsightsClientV2UnitTest.kt
> Add analytics events (excluding manage_customer_session_recommendations)

- CHANGELOG.md
- Fix unreleased header in changelog
> Fix unreleased header in changelog

- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalPhoneNumber.kt
- Update `PayPalPhoneNumber` doc string to call out formatting rules
> Update PayPalPhoneNumber doc string

- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsFragmentV2.kt
- Demo/src/main/java/com/braintreepayments/demo/ShopperInsightsV2ViewModel.kt
Updates to payment ready v2 demo app so it's showing outcomes of the network calls.
@jwarmkessel @warmkesselj
> Payment ready v2 update demo

- CHANGELOG.md
- Demo/src/main/java/com/braintreepayments/demo/PayPalFragment.java
- Demo/src/main/java/com/braintreepayments/demo/PayPalRequestFactory.java
- Demo/src/main/res/layout/fragment_paypal.xml
- Demo/src/main/res/values/strings.xml
- PayPal/src/main/java/com/braintreepayments/api/paypal/PayPalInternalClient.kt
- PayPal/src/test/java/com/braintreepayments/api/paypal/PayPalInternalClientUnitTest.kt
- Added new query parameters that will be required from the PayPal app switch universal link. 
- Updated the Demo App so that we'd be able to test the Pay Later functionality. 
> @anibalb2500
Showcases running with the new toggled and then untoggled. 
https://github.com/user-attachments/assets/0fd9a310-8b9c-4865-be99-672be264fe43
> Add required query params
